image: golang:1.7

test:
  script:
    - "# Check for the mistake of updating .proto files but not regenerating clients"
    - apt-get update -qq
    - apt-get install -qq -y rubygems bundler unzip
    - _support/check-grpc-proto-clients
