image: golang:1.11

before_script:
  - apt-get update -qq
  - apt-get install -qq -y rubygems bundler unzip

test:
  script:
    - make test

build:
  script:
    - make

check-grpc-proto-clients:
  script:
    - "# Check for the mistake of updating .proto files but not regenerating clients"
    - make check-grpc-proto-clients

pages:
  script:
    - make docs
  artifacts:
    paths:
    - public
  only:
  - master
