image: golang:1.11

cache:
  paths:
    - .go/pkg/mod/

variables:
  GOPATH: $CI_PROJECT_DIR/.go

before_script:
  - apt-get update -qq
  - apt-get install -qq -y rubygems bundler unzip
  - mkdir -p .go

cache:
  key: go-mod-cache
  paths:
    - ${GOPATH}/pkg/mod

test:
  script:
    - make test

build:
  script:
    - make

check-grpc-proto-clients:
  script:
    - "# Check for the mistake of updating .proto files but not regenerating clients"
    - make check-grpc-proto-clients

pages:
  script:
    - make docs
  artifacts:
    paths:
    - public
  only:
  - master

danger-review:
  image: registry.gitlab.com/gitlab-org/gitlab-build-images:danger
  before_script: []
  cache: {}
  only:
    - branches@gitlab-org/gitaly-proto
  except:
    - tags
    - master
  script:
    - git version
    - danger
