image: golang:1.10

before_script:
  - apt-get update -qq
  - apt-get install -qq -y rubygems bundler unzip

build:
  script:
    - make

lint:
  before_script: []
  script:
    - go get -u gitlab.com/pokstad1/protoc-gen-gitaly
    - protoc --gitaly_out=. *.proto

check-grpc-proto-clients:
  script:
    - "# Check for the mistake of updating .proto files but not regenerating clients"
    - make check-grpc-proto-clients

pages:
  script:
    - make docs
  artifacts:
    paths:
    - public
  only:
  - master
