// Code generated by protoc-gen-go. DO NOT EDIT.
// source: go/internal/linter/testdata/invalid.proto

package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "gitlab.com/gitlab-org/gitaly-proto/go/gitalypb"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InvalidMethodRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidMethodRequest) Reset()         { *m = InvalidMethodRequest{} }
func (m *InvalidMethodRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidMethodRequest) ProtoMessage()    {}
func (*InvalidMethodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_invalid_8e27a3d25dd6dc36, []int{0}
}
func (m *InvalidMethodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidMethodRequest.Unmarshal(m, b)
}
func (m *InvalidMethodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidMethodRequest.Marshal(b, m, deterministic)
}
func (dst *InvalidMethodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidMethodRequest.Merge(dst, src)
}
func (m *InvalidMethodRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidMethodRequest.Size(m)
}
func (m *InvalidMethodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidMethodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidMethodRequest proto.InternalMessageInfo

type InvalidTargetType struct {
	WrongType            int32    `protobuf:"varint,1,opt,name=wrong_type,json=wrongType,proto3" json:"wrong_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidTargetType) Reset()         { *m = InvalidTargetType{} }
func (m *InvalidTargetType) String() string { return proto.CompactTextString(m) }
func (*InvalidTargetType) ProtoMessage()    {}
func (*InvalidTargetType) Descriptor() ([]byte, []int) {
	return fileDescriptor_invalid_8e27a3d25dd6dc36, []int{1}
}
func (m *InvalidTargetType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidTargetType.Unmarshal(m, b)
}
func (m *InvalidTargetType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidTargetType.Marshal(b, m, deterministic)
}
func (dst *InvalidTargetType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidTargetType.Merge(dst, src)
}
func (m *InvalidTargetType) XXX_Size() int {
	return xxx_messageInfo_InvalidTargetType.Size(m)
}
func (m *InvalidTargetType) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidTargetType.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidTargetType proto.InternalMessageInfo

func (m *InvalidTargetType) GetWrongType() int32 {
	if m != nil {
		return m.WrongType
	}
	return 0
}

type InvalidMethodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InvalidMethodResponse) Reset()         { *m = InvalidMethodResponse{} }
func (m *InvalidMethodResponse) String() string { return proto.CompactTextString(m) }
func (*InvalidMethodResponse) ProtoMessage()    {}
func (*InvalidMethodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_invalid_8e27a3d25dd6dc36, []int{2}
}
func (m *InvalidMethodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidMethodResponse.Unmarshal(m, b)
}
func (m *InvalidMethodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidMethodResponse.Marshal(b, m, deterministic)
}
func (dst *InvalidMethodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidMethodResponse.Merge(dst, src)
}
func (m *InvalidMethodResponse) XXX_Size() int {
	return xxx_messageInfo_InvalidMethodResponse.Size(m)
}
func (m *InvalidMethodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidMethodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidMethodResponse proto.InternalMessageInfo

type InvalidNestedRequest struct {
	InnerMessage         *InvalidTargetType `protobuf:"bytes,1,opt,name=inner_message,json=innerMessage,proto3" json:"inner_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *InvalidNestedRequest) Reset()         { *m = InvalidNestedRequest{} }
func (m *InvalidNestedRequest) String() string { return proto.CompactTextString(m) }
func (*InvalidNestedRequest) ProtoMessage()    {}
func (*InvalidNestedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_invalid_8e27a3d25dd6dc36, []int{3}
}
func (m *InvalidNestedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InvalidNestedRequest.Unmarshal(m, b)
}
func (m *InvalidNestedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InvalidNestedRequest.Marshal(b, m, deterministic)
}
func (dst *InvalidNestedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InvalidNestedRequest.Merge(dst, src)
}
func (m *InvalidNestedRequest) XXX_Size() int {
	return xxx_messageInfo_InvalidNestedRequest.Size(m)
}
func (m *InvalidNestedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InvalidNestedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InvalidNestedRequest proto.InternalMessageInfo

func (m *InvalidNestedRequest) GetInnerMessage() *InvalidTargetType {
	if m != nil {
		return m.InnerMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*InvalidMethodRequest)(nil), "test.InvalidMethodRequest")
	proto.RegisterType((*InvalidTargetType)(nil), "test.InvalidTargetType")
	proto.RegisterType((*InvalidMethodResponse)(nil), "test.InvalidMethodResponse")
	proto.RegisterType((*InvalidNestedRequest)(nil), "test.InvalidNestedRequest")
}

func init() {
	proto.RegisterFile("go/internal/linter/testdata/invalid.proto", fileDescriptor_invalid_8e27a3d25dd6dc36)
}

var fileDescriptor_invalid_8e27a3d25dd6dc36 = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0xd4, 0xcd, 0x4e, 0xab, 0x40,
	0x14, 0x07, 0xf0, 0x4b, 0x6f, 0x3f, 0xe8, 0xb4, 0xf7, 0xaa, 0x13, 0xb5, 0x06, 0x63, 0x62, 0x58,
	0xe1, 0x06, 0x0a, 0xf5, 0x33, 0xf1, 0x05, 0x8c, 0xa9, 0x89, 0x2d, 0xb1, 0xcb, 0x06, 0xed, 0x09,
	0x25, 0xa9, 0x03, 0xce, 0x8c, 0x35, 0x7d, 0x0b, 0x77, 0x2c, 0x5c, 0xf8, 0x16, 0x3e, 0x97, 0x6b,
	0x56, 0xa6, 0x80, 0x4d, 0x18, 0x6a, 0xd2, 0x50, 0x77, 0xcd, 0x99, 0x93, 0xdf, 0xf9, 0x4f, 0x39,
	0x80, 0x8e, 0x5c, 0xdf, 0xf0, 0x08, 0x07, 0x4a, 0x9c, 0x89, 0x31, 0x89, 0x7f, 0x19, 0x1c, 0x18,
	0x1f, 0x39, 0xdc, 0x31, 0x3c, 0x32, 0x75, 0x26, 0xde, 0x48, 0x0f, 0xa8, 0xcf, 0x7d, 0x5c, 0x9e,
	0xd7, 0x95, 0x26, 0x1b, 0x3b, 0x14, 0xd2, 0x9a, 0xba, 0x8b, 0xb6, 0xaf, 0x92, 0xa6, 0x2e, 0xf0,
	0xb1, 0x3f, 0xea, 0xc1, 0xd3, 0x33, 0x30, 0xae, 0x5a, 0x68, 0x2b, 0xad, 0xdb, 0x0e, 0x75, 0x81,
	0xdb, 0xb3, 0x00, 0xf0, 0x01, 0x42, 0x2f, 0xd4, 0x27, 0xee, 0x90, 0xcf, 0x02, 0xd8, 0x93, 0x0e,
	0x25, 0xad, 0xd2, 0xab, 0xc7, 0x95, 0xf9, 0xb1, 0xda, 0x42, 0x3b, 0x82, 0xc5, 0x02, 0x9f, 0x30,
	0x50, 0xed, 0xc5, 0x90, 0x1b, 0x60, 0x1c, 0xbe, 0x87, 0xe0, 0x4b, 0xf4, 0xcf, 0x23, 0x04, 0xe8,
	0xf0, 0x11, 0x18, 0x73, 0xdc, 0x84, 0x6c, 0x58, 0x2d, 0x7d, 0x1e, 0x54, 0xcf, 0xcd, 0xef, 0x35,
	0xe3, 0xee, 0x6e, 0xd2, 0x6c, 0x7d, 0xd4, 0xd0, 0xff, 0xb4, 0xa7, 0x0f, 0x74, 0xea, 0x3d, 0x00,
	0xbe, 0x5e, 0x54, 0x92, 0x04, 0x6d, 0xac, 0x64, 0xac, 0xcc, 0x1d, 0x95, 0xfd, 0xa5, 0x67, 0x69,
	0xe6, 0x3f, 0xf8, 0x56, 0xc0, 0xcc, 0xe2, 0x58, 0x35, 0x0a, 0xb5, 0x92, 0x9c, 0x27, 0xad, 0x75,
	0xc9, 0x12, 0xbe, 0x13, 0xc8, 0x4e, 0x71, 0xb2, 0x11, 0x85, 0x5a, 0x4d, 0x96, 0x36, 0x25, 0x45,
	0x32, 0x73, 0x51, 0x8f, 0xd7, 0x8d, 0x2a, 0xe1, 0x81, 0x40, 0x9e, 0x14, 0x27, 0x9b, 0x51, 0xa8,
	0xc9, 0xb2, 0xa4, 0x94, 0x3f, 0xdf, 0x5f, 0xdf, 0xb0, 0x2d, 0xc0, 0xa7, 0xc5, 0xe1, 0x7a, 0x14,
	0x6a, 0x15, 0x79, 0xe9, 0x3f, 0x70, 0x86, 0x7f, 0x5a, 0xcc, 0x95, 0xc9, 0xbe, 0x40, 0x9e, 0x17,
	0x24, 0xd3, 0x27, 0xa5, 0xfc, 0x35, 0x75, 0x33, 0xb7, 0x01, 0x17, 0xc2, 0xed, 0x33, 0xef, 0xdc,
	0xca, 0xae, 0x85, 0x07, 0x68, 0x23, 0xbb, 0xff, 0xed, 0x5f, 0x81, 0xcd, 0xfb, 0x6a, 0xfc, 0xe9,
	0xe9, 0x7c, 0x05, 0x00, 0x00, 0xff, 0xff, 0x63, 0xe5, 0x98, 0xea, 0xbb, 0x04, 0x00, 0x00,
}
