# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: info.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gitaly.server.InfoRequest" do
  end
  add_message "gitaly.server.InfoResponse" do
    optional :server_version, :string, 1
    optional :git_version, :string, 2
  end
end

module Gitaly
  module Server
    InfoRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.server.InfoRequest").msgclass
    InfoResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.server.InfoResponse").msgclass
  end
end
