// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blob.proto

/*
Package gitaly is a generated protocol buffer package.

It is generated from these files:
	blob.proto
	commit.proto
	conflicts.proto
	deprecated-services.proto
	diff.proto
	namespace.proto
	notifications.proto
	operations.proto
	ref.proto
	repository-service.proto
	shared.proto
	smarthttp.proto
	ssh.proto
	wiki.proto

It has these top-level messages:
	GetBlobRequest
	GetBlobResponse
	GetBlobsRequest
	GetBlobsResponse
	ListBlobsByRevisionPathsRequest
	ListBlobsByRevisionPathsResponse
	CommitStatsRequest
	CommitStatsResponse
	CommitIsAncestorRequest
	CommitIsAncestorResponse
	TreeEntryRequest
	TreeEntryResponse
	CommitsBetweenRequest
	CommitsBetweenResponse
	CountCommitsRequest
	CountCommitsResponse
	TreeEntry
	GetTreeEntriesRequest
	GetTreeEntriesResponse
	ListFilesRequest
	ListFilesResponse
	FindCommitRequest
	FindCommitResponse
	ListCommitsByOidRequest
	ListCommitsByOidResponse
	FindAllCommitsRequest
	FindAllCommitsResponse
	FindCommitsRequest
	FindCommitsResponse
	CommitLanguagesRequest
	CommitLanguagesResponse
	RawBlameRequest
	RawBlameResponse
	LastCommitForPathRequest
	LastCommitForPathResponse
	CommitsByMessageRequest
	CommitsByMessageResponse
	FilterShasWithSignaturesRequest
	FilterShasWithSignaturesResponse
	ListConflictFilesRequest
	ConflictFileHeader
	ConflictFile
	ListConflictFilesResponse
	ResolveConflictsRequestHeader
	ResolveConflictsRequest
	ResolveConflictsResponse
	CommitDiffRequest
	CommitDiffResponse
	CommitDeltaRequest
	CommitDelta
	CommitDeltaResponse
	CommitPatchRequest
	CommitPatchResponse
	RawDiffRequest
	RawDiffResponse
	RawPatchRequest
	RawPatchResponse
	AddNamespaceRequest
	RemoveNamespaceRequest
	RenameNamespaceRequest
	NamespaceExistsRequest
	NamespaceExistsResponse
	AddNamespaceResponse
	RemoveNamespaceResponse
	RenameNamespaceResponse
	PostReceiveRequest
	PostReceiveResponse
	UserCreateBranchRequest
	UserCreateBranchResponse
	UserDeleteBranchRequest
	UserDeleteBranchResponse
	UserDeleteTagRequest
	UserDeleteTagResponse
	UserCreateTagRequest
	UserCreateTagResponse
	UserMergeBranchRequest
	UserMergeBranchResponse
	OperationBranchUpdate
	UserFFBranchRequest
	UserFFBranchResponse
	UserCherryPickRequest
	UserCherryPickResponse
	UserRevertRequest
	UserRevertResponse
	FindDefaultBranchNameRequest
	FindDefaultBranchNameResponse
	FindAllBranchNamesRequest
	FindAllBranchNamesResponse
	FindAllTagNamesRequest
	FindAllTagNamesResponse
	FindRefNameRequest
	FindRefNameResponse
	FindLocalBranchesRequest
	FindLocalBranchesResponse
	FindLocalBranchResponse
	FindLocalBranchCommitAuthor
	FindAllBranchesRequest
	FindAllBranchesResponse
	FindAllTagsRequest
	FindAllTagsResponse
	RefExistsRequest
	RefExistsResponse
	CreateBranchRequest
	CreateBranchResponse
	DeleteBranchRequest
	DeleteBranchResponse
	FindBranchRequest
	FindBranchResponse
	DeleteRefsRequest
	DeleteRefsResponse
	RepositoryExistsRequest
	RepositoryExistsResponse
	RepositoryIsEmptyRequest
	RepositoryIsEmptyResponse
	RepackIncrementalRequest
	RepackIncrementalResponse
	RepackFullRequest
	RepackFullResponse
	GarbageCollectRequest
	GarbageCollectResponse
	RepositorySizeRequest
	RepositorySizeResponse
	ApplyGitattributesRequest
	ApplyGitattributesResponse
	FetchRemoteRequest
	FetchRemoteResponse
	CreateRepositoryRequest
	CreateRepositoryResponse
	GetArchiveRequest
	GetArchiveResponse
	HasLocalBranchesRequest
	HasLocalBranchesResponse
	ChangeStorageRequest
	ChangeStorageResponse
	FetchSourceBranchRequest
	FetchSourceBranchResponse
	FsckRequest
	FsckResponse
	WriteRefRequest
	WriteRefResponse
	FindMergeBaseRequest
	FindMergeBaseResponse
	Repository
	GitCommit
	CommitAuthor
	ExitStatus
	Branch
	Tag
	User
	InfoRefsRequest
	InfoRefsResponse
	PostUploadPackRequest
	PostUploadPackResponse
	PostReceivePackRequest
	PostReceivePackResponse
	SSHUploadPackRequest
	SSHUploadPackResponse
	SSHReceivePackRequest
	SSHReceivePackResponse
	WikiCommitDetails
	WikiPageVersion
	WikiPage
	WikiGetPageVersionsRequest
	WikiGetPageVersionsResponse
	WikiWritePageRequest
	WikiWritePageResponse
	WikiUpdatePageRequest
	WikiUpdatePageResponse
	WikiDeletePageRequest
	WikiDeletePageResponse
	WikiFindPageRequest
	WikiFindPageResponse
	WikiFindFileRequest
	WikiFindFileResponse
	WikiGetAllPagesRequest
	WikiGetAllPagesResponse
*/
package gitaly

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetBlobRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	// Object ID (SHA1) of the blob we want to get
	Oid string `protobuf:"bytes,2,opt,name=oid" json:"oid,omitempty"`
	// Maximum number of bytes we want to receive. Use '-1' to get the full blob no matter how big.
	Limit int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetBlobRequest) Reset()                    { *m = GetBlobRequest{} }
func (m *GetBlobRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlobRequest) ProtoMessage()               {}
func (*GetBlobRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetBlobRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *GetBlobRequest) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *GetBlobRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetBlobResponse struct {
	// Blob size; present only in first response message
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	// Chunk of blob data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Object ID of the actual blob returned. Empty if no blob was found.
	Oid string `protobuf:"bytes,3,opt,name=oid" json:"oid,omitempty"`
}

func (m *GetBlobResponse) Reset()                    { *m = GetBlobResponse{} }
func (m *GetBlobResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlobResponse) ProtoMessage()               {}
func (*GetBlobResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetBlobResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetBlobResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetBlobResponse) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

type GetBlobsRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	// Object IDs (SHA1) of the blobs we want to get
	Oids []string `protobuf:"bytes,2,rep,name=oids" json:"oids,omitempty"`
	// Maximum number of bytes we want to receive. Use '-1' to get the full blobs no matter how big.
	Limit int64 `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *GetBlobsRequest) Reset()                    { *m = GetBlobsRequest{} }
func (m *GetBlobsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBlobsRequest) ProtoMessage()               {}
func (*GetBlobsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetBlobsRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *GetBlobsRequest) GetOids() []string {
	if m != nil {
		return m.Oids
	}
	return nil
}

func (m *GetBlobsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetBlobsResponse struct {
	// Blob size; present only on the first message per blob
	Size int64 `protobuf:"varint,1,opt,name=size" json:"size,omitempty"`
	// Chunk of blob data
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Object ID of the current blob. Only present on the first message per blob. Empty if no blob was found.
	Oid string `protobuf:"bytes,3,opt,name=oid" json:"oid,omitempty"`
}

func (m *GetBlobsResponse) Reset()                    { *m = GetBlobsResponse{} }
func (m *GetBlobsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetBlobsResponse) ProtoMessage()               {}
func (*GetBlobsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetBlobsResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *GetBlobsResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *GetBlobsResponse) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

type ListBlobsByRevisionPathsRequest struct {
	Repository    *Repository                                     `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	RevisionPaths []*ListBlobsByRevisionPathsRequest_RevisionPath `protobuf:"bytes,2,rep,name=revision_paths,json=revisionPaths" json:"revision_paths,omitempty"`
}

func (m *ListBlobsByRevisionPathsRequest) Reset()                    { *m = ListBlobsByRevisionPathsRequest{} }
func (m *ListBlobsByRevisionPathsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListBlobsByRevisionPathsRequest) ProtoMessage()               {}
func (*ListBlobsByRevisionPathsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListBlobsByRevisionPathsRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *ListBlobsByRevisionPathsRequest) GetRevisionPaths() []*ListBlobsByRevisionPathsRequest_RevisionPath {
	if m != nil {
		return m.RevisionPaths
	}
	return nil
}

type ListBlobsByRevisionPathsRequest_RevisionPath struct {
	Revision string `protobuf:"bytes,1,opt,name=revision" json:"revision,omitempty"`
	Path     string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Limit    int64  `protobuf:"varint,3,opt,name=limit" json:"limit,omitempty"`
}

func (m *ListBlobsByRevisionPathsRequest_RevisionPath) Reset() {
	*m = ListBlobsByRevisionPathsRequest_RevisionPath{}
}
func (m *ListBlobsByRevisionPathsRequest_RevisionPath) String() string {
	return proto.CompactTextString(m)
}
func (*ListBlobsByRevisionPathsRequest_RevisionPath) ProtoMessage() {}
func (*ListBlobsByRevisionPathsRequest_RevisionPath) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4, 0}
}

func (m *ListBlobsByRevisionPathsRequest_RevisionPath) GetRevision() string {
	if m != nil {
		return m.Revision
	}
	return ""
}

func (m *ListBlobsByRevisionPathsRequest_RevisionPath) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *ListBlobsByRevisionPathsRequest_RevisionPath) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type ListBlobsByRevisionPathsResponse struct {
	Oid  string `protobuf:"bytes,1,opt,name=oid" json:"oid,omitempty"`
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Size int64  `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
}

func (m *ListBlobsByRevisionPathsResponse) Reset()         { *m = ListBlobsByRevisionPathsResponse{} }
func (m *ListBlobsByRevisionPathsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBlobsByRevisionPathsResponse) ProtoMessage()    {}
func (*ListBlobsByRevisionPathsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

func (m *ListBlobsByRevisionPathsResponse) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *ListBlobsByRevisionPathsResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListBlobsByRevisionPathsResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func init() {
	proto.RegisterType((*GetBlobRequest)(nil), "gitaly.GetBlobRequest")
	proto.RegisterType((*GetBlobResponse)(nil), "gitaly.GetBlobResponse")
	proto.RegisterType((*GetBlobsRequest)(nil), "gitaly.GetBlobsRequest")
	proto.RegisterType((*GetBlobsResponse)(nil), "gitaly.GetBlobsResponse")
	proto.RegisterType((*ListBlobsByRevisionPathsRequest)(nil), "gitaly.ListBlobsByRevisionPathsRequest")
	proto.RegisterType((*ListBlobsByRevisionPathsRequest_RevisionPath)(nil), "gitaly.ListBlobsByRevisionPathsRequest.RevisionPath")
	proto.RegisterType((*ListBlobsByRevisionPathsResponse)(nil), "gitaly.ListBlobsByRevisionPathsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlobService service

type BlobServiceClient interface {
	// GetBlob returns the contents of a blob object referenced by its object
	// ID. We use a stream to return a chunked arbitrarily large binary
	// response
	GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (BlobService_GetBlobClient, error)
	// GetBlobsBySHA returns the contents of a blob objects referenced by their object
	// ID. We use a stream to return a chunked arbitrarily large binary response.
	// The blobs are sent in a continous stream, the caller is responsible for spliting
	// them up into multiple blobs by their object IDs.
	GetBlobs(ctx context.Context, in *GetBlobsRequest, opts ...grpc.CallOption) (BlobService_GetBlobsClient, error)
	// ListBlobsByRevisionPath returns the blob for each (commit_oid, path) passed in
	// Commit oid and path can vary between each request and might not have any relation to each other
	ListBlobsByRevisionPaths(ctx context.Context, in *ListBlobsByRevisionPathsRequest, opts ...grpc.CallOption) (BlobService_ListBlobsByRevisionPathsClient, error)
}

type blobServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlobServiceClient(cc *grpc.ClientConn) BlobServiceClient {
	return &blobServiceClient{cc}
}

func (c *blobServiceClient) GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (BlobService_GetBlobClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BlobService_serviceDesc.Streams[0], c.cc, "/gitaly.BlobService/GetBlob", opts...)
	if err != nil {
		return nil, err
	}
	x := &blobServiceGetBlobClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlobService_GetBlobClient interface {
	Recv() (*GetBlobResponse, error)
	grpc.ClientStream
}

type blobServiceGetBlobClient struct {
	grpc.ClientStream
}

func (x *blobServiceGetBlobClient) Recv() (*GetBlobResponse, error) {
	m := new(GetBlobResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *blobServiceClient) GetBlobs(ctx context.Context, in *GetBlobsRequest, opts ...grpc.CallOption) (BlobService_GetBlobsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BlobService_serviceDesc.Streams[1], c.cc, "/gitaly.BlobService/GetBlobs", opts...)
	if err != nil {
		return nil, err
	}
	x := &blobServiceGetBlobsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlobService_GetBlobsClient interface {
	Recv() (*GetBlobsResponse, error)
	grpc.ClientStream
}

type blobServiceGetBlobsClient struct {
	grpc.ClientStream
}

func (x *blobServiceGetBlobsClient) Recv() (*GetBlobsResponse, error) {
	m := new(GetBlobsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *blobServiceClient) ListBlobsByRevisionPaths(ctx context.Context, in *ListBlobsByRevisionPathsRequest, opts ...grpc.CallOption) (BlobService_ListBlobsByRevisionPathsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BlobService_serviceDesc.Streams[2], c.cc, "/gitaly.BlobService/ListBlobsByRevisionPaths", opts...)
	if err != nil {
		return nil, err
	}
	x := &blobServiceListBlobsByRevisionPathsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlobService_ListBlobsByRevisionPathsClient interface {
	Recv() (*ListBlobsByRevisionPathsResponse, error)
	grpc.ClientStream
}

type blobServiceListBlobsByRevisionPathsClient struct {
	grpc.ClientStream
}

func (x *blobServiceListBlobsByRevisionPathsClient) Recv() (*ListBlobsByRevisionPathsResponse, error) {
	m := new(ListBlobsByRevisionPathsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for BlobService service

type BlobServiceServer interface {
	// GetBlob returns the contents of a blob object referenced by its object
	// ID. We use a stream to return a chunked arbitrarily large binary
	// response
	GetBlob(*GetBlobRequest, BlobService_GetBlobServer) error
	// GetBlobsBySHA returns the contents of a blob objects referenced by their object
	// ID. We use a stream to return a chunked arbitrarily large binary response.
	// The blobs are sent in a continous stream, the caller is responsible for spliting
	// them up into multiple blobs by their object IDs.
	GetBlobs(*GetBlobsRequest, BlobService_GetBlobsServer) error
	// ListBlobsByRevisionPath returns the blob for each (commit_oid, path) passed in
	// Commit oid and path can vary between each request and might not have any relation to each other
	ListBlobsByRevisionPaths(*ListBlobsByRevisionPathsRequest, BlobService_ListBlobsByRevisionPathsServer) error
}

func RegisterBlobServiceServer(s *grpc.Server, srv BlobServiceServer) {
	s.RegisterService(&_BlobService_serviceDesc, srv)
}

func _BlobService_GetBlob_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlobRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobServiceServer).GetBlob(m, &blobServiceGetBlobServer{stream})
}

type BlobService_GetBlobServer interface {
	Send(*GetBlobResponse) error
	grpc.ServerStream
}

type blobServiceGetBlobServer struct {
	grpc.ServerStream
}

func (x *blobServiceGetBlobServer) Send(m *GetBlobResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BlobService_GetBlobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBlobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobServiceServer).GetBlobs(m, &blobServiceGetBlobsServer{stream})
}

type BlobService_GetBlobsServer interface {
	Send(*GetBlobsResponse) error
	grpc.ServerStream
}

type blobServiceGetBlobsServer struct {
	grpc.ServerStream
}

func (x *blobServiceGetBlobsServer) Send(m *GetBlobsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BlobService_ListBlobsByRevisionPaths_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListBlobsByRevisionPathsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlobServiceServer).ListBlobsByRevisionPaths(m, &blobServiceListBlobsByRevisionPathsServer{stream})
}

type BlobService_ListBlobsByRevisionPathsServer interface {
	Send(*ListBlobsByRevisionPathsResponse) error
	grpc.ServerStream
}

type blobServiceListBlobsByRevisionPathsServer struct {
	grpc.ServerStream
}

func (x *blobServiceListBlobsByRevisionPathsServer) Send(m *ListBlobsByRevisionPathsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _BlobService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.BlobService",
	HandlerType: (*BlobServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBlob",
			Handler:       _BlobService_GetBlob_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetBlobs",
			Handler:       _BlobService_GetBlobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListBlobsByRevisionPaths",
			Handler:       _BlobService_ListBlobsByRevisionPaths_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blob.proto",
}

func init() { proto.RegisterFile("blob.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x41, 0x4f, 0xab, 0x40,
	0x10, 0x7e, 0x40, 0x5f, 0x5f, 0x3b, 0xed, 0xeb, 0x6b, 0x26, 0x2f, 0x4a, 0xb8, 0x48, 0xb8, 0xc8,
	0x89, 0x18, 0xf4, 0x6c, 0x62, 0x2f, 0x1e, 0xec, 0xc1, 0xac, 0xde, 0x34, 0x31, 0x20, 0x1b, 0xbb,
	0x09, 0x76, 0x29, 0xbb, 0x36, 0xa9, 0x57, 0x2f, 0xfe, 0x6c, 0xc3, 0xc2, 0x02, 0x5a, 0x49, 0x4d,
	0x7a, 0x9b, 0x9d, 0x9d, 0xfd, 0xbe, 0x6f, 0xbe, 0x99, 0x05, 0x88, 0x53, 0x1e, 0x07, 0x59, 0xce,
	0x25, 0xc7, 0xfe, 0x13, 0x93, 0x51, 0xba, 0x71, 0xc6, 0x62, 0x11, 0xe5, 0x34, 0x29, 0xb3, 0x5e,
	0x0a, 0x93, 0x4b, 0x2a, 0x67, 0x29, 0x8f, 0x09, 0x5d, 0xbd, 0x50, 0x21, 0x31, 0x04, 0xc8, 0x69,
	0xc6, 0x05, 0x93, 0x3c, 0xdf, 0xd8, 0x86, 0x6b, 0xf8, 0xa3, 0x10, 0x83, 0xf2, 0x71, 0x40, 0xea,
	0x1b, 0xd2, 0xaa, 0xc2, 0x29, 0x58, 0x9c, 0x25, 0xb6, 0xe9, 0x1a, 0xfe, 0x90, 0x14, 0x21, 0xfe,
	0x87, 0xdf, 0x29, 0x7b, 0x66, 0xd2, 0xb6, 0x5c, 0xc3, 0xb7, 0x48, 0x79, 0xf0, 0xae, 0xe0, 0x5f,
	0xcd, 0x26, 0x32, 0xbe, 0x14, 0x14, 0x11, 0x7a, 0x82, 0xbd, 0x52, 0x45, 0x64, 0x11, 0x15, 0x17,
	0xb9, 0x24, 0x92, 0x91, 0xc2, 0x1b, 0x13, 0x15, 0x6b, 0x0a, 0xab, 0xa6, 0xf0, 0x78, 0x0d, 0x26,
	0xf6, 0xd1, 0x8e, 0xd0, 0xe3, 0x2c, 0x11, 0xb6, 0xe9, 0x5a, 0xfe, 0x90, 0xa8, 0xb8, 0x43, 0xfd,
	0x1c, 0xa6, 0x0d, 0xe1, 0xde, 0xf2, 0xdf, 0x4d, 0x38, 0x9a, 0x33, 0x51, 0xe2, 0xcd, 0x36, 0x84,
	0xae, 0x99, 0x60, 0x7c, 0x79, 0x1d, 0xc9, 0xc5, 0x5e, 0xfd, 0xdc, 0xc1, 0x24, 0xaf, 0xb0, 0x1e,
	0xb2, 0x02, 0x4c, 0x75, 0x36, 0x0a, 0xcf, 0xf4, 0xbb, 0x1d, 0xa4, 0x41, 0x3b, 0x49, 0xfe, 0xe6,
	0xed, 0x12, 0xe7, 0x16, 0xc6, 0xed, 0x6b, 0x74, 0x60, 0xa0, 0x0b, 0x94, 0xbc, 0x21, 0xa9, 0xcf,
	0x85, 0x0d, 0x05, 0x7f, 0xb5, 0x15, 0x2a, 0xee, 0x30, 0xf6, 0x1e, 0xdc, 0x6e, 0x51, 0x95, 0xd1,
	0x95, 0x81, 0x46, 0xb3, 0x62, 0xdf, 0xd9, 0xac, 0xc7, 0x61, 0x35, 0xe3, 0x08, 0xdf, 0x4c, 0x18,
	0x15, 0xd0, 0x37, 0x34, 0x5f, 0xb3, 0x47, 0x8a, 0xe7, 0xf0, 0xa7, 0x1a, 0x23, 0x1e, 0x68, 0x4f,
	0x3e, 0xff, 0x01, 0xe7, 0x70, 0x2b, 0x5f, 0xaa, 0xf0, 0x7e, 0x9d, 0x18, 0x78, 0x01, 0x03, 0xbd,
	0x06, 0xf8, 0xb5, 0x50, 0x9b, 0xe8, 0xd8, 0xdb, 0x17, 0x2d, 0x88, 0x15, 0xd8, 0x5d, 0x0d, 0xe3,
	0xf1, 0x0f, 0xe7, 0xe4, 0xf8, 0xbb, 0x0b, 0x1b, 0xca, 0xb8, 0xaf, 0xfe, 0xfb, 0xe9, 0x47, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x92, 0x78, 0xda, 0xe9, 0x13, 0x04, 0x00, 0x00,
}
