// Code generated by protoc-gen-go. DO NOT EDIT.
// source: commit.proto

/*
Package gitaly is a generated protocol buffer package.

It is generated from these files:
	commit.proto
	diff.proto
	notifications.proto
	ref.proto
	repository.proto
	shared.proto
	smarthttp.proto
	ssh.proto

It has these top-level messages:
	CommitIsAncestorRequest
	CommitIsAncestorResponse
	TreeEntryRequest
	TreeEntryResponse
	CommitDiffRequest
	CommitDiffResponse
	CommitDeltaRequest
	CommitDelta
	CommitDeltaResponse
	PostReceiveRequest
	PostReceiveResponse
	FindDefaultBranchNameRequest
	FindDefaultBranchNameResponse
	FindAllBranchNamesRequest
	FindAllBranchNamesResponse
	FindAllTagNamesRequest
	FindAllTagNamesResponse
	FindRefNameRequest
	FindRefNameResponse
	FindLocalBranchesRequest
	FindLocalBranchesResponse
	FindLocalBranchResponse
	FindLocalBranchCommitAuthor
	Repository
	RepositoryExistsRequest
	RepositoryExistsResponse
	ExitStatus
	InfoRefsRequest
	InfoRefsResponse
	PostUploadPackRequest
	PostUploadPackResponse
	PostReceivePackRequest
	PostReceivePackResponse
	SSHUploadPackRequest
	SSHUploadPackResponse
	SSHReceivePackRequest
	SSHReceivePackResponse
*/
package gitaly

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TreeEntryResponse_ObjectType int32

const (
	TreeEntryResponse_COMMIT TreeEntryResponse_ObjectType = 0
	TreeEntryResponse_BLOB   TreeEntryResponse_ObjectType = 1
	TreeEntryResponse_TREE   TreeEntryResponse_ObjectType = 2
	TreeEntryResponse_TAG    TreeEntryResponse_ObjectType = 3
)

var TreeEntryResponse_ObjectType_name = map[int32]string{
	0: "COMMIT",
	1: "BLOB",
	2: "TREE",
	3: "TAG",
}
var TreeEntryResponse_ObjectType_value = map[string]int32{
	"COMMIT": 0,
	"BLOB":   1,
	"TREE":   2,
	"TAG":    3,
}

func (x TreeEntryResponse_ObjectType) String() string {
	return proto.EnumName(TreeEntryResponse_ObjectType_name, int32(x))
}
func (TreeEntryResponse_ObjectType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3, 0}
}

type CommitIsAncestorRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	AncestorId string      `protobuf:"bytes,2,opt,name=ancestor_id,json=ancestorId" json:"ancestor_id,omitempty"`
	ChildId    string      `protobuf:"bytes,3,opt,name=child_id,json=childId" json:"child_id,omitempty"`
}

func (m *CommitIsAncestorRequest) Reset()                    { *m = CommitIsAncestorRequest{} }
func (m *CommitIsAncestorRequest) String() string            { return proto.CompactTextString(m) }
func (*CommitIsAncestorRequest) ProtoMessage()               {}
func (*CommitIsAncestorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CommitIsAncestorRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *CommitIsAncestorRequest) GetAncestorId() string {
	if m != nil {
		return m.AncestorId
	}
	return ""
}

func (m *CommitIsAncestorRequest) GetChildId() string {
	if m != nil {
		return m.ChildId
	}
	return ""
}

type CommitIsAncestorResponse struct {
	Value bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *CommitIsAncestorResponse) Reset()                    { *m = CommitIsAncestorResponse{} }
func (m *CommitIsAncestorResponse) String() string            { return proto.CompactTextString(m) }
func (*CommitIsAncestorResponse) ProtoMessage()               {}
func (*CommitIsAncestorResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CommitIsAncestorResponse) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type TreeEntryRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	Revision   []byte      `protobuf:"bytes,2,opt,name=revision,proto3" json:"revision,omitempty"`
	Path       []byte      `protobuf:"bytes,3,opt,name=path,proto3" json:"path,omitempty"`
	Limit      int64       `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
}

func (m *TreeEntryRequest) Reset()                    { *m = TreeEntryRequest{} }
func (m *TreeEntryRequest) String() string            { return proto.CompactTextString(m) }
func (*TreeEntryRequest) ProtoMessage()               {}
func (*TreeEntryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *TreeEntryRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *TreeEntryRequest) GetRevision() []byte {
	if m != nil {
		return m.Revision
	}
	return nil
}

func (m *TreeEntryRequest) GetPath() []byte {
	if m != nil {
		return m.Path
	}
	return nil
}

func (m *TreeEntryRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type TreeEntryResponse struct {
	Type TreeEntryResponse_ObjectType `protobuf:"varint,1,opt,name=type,enum=gitaly.TreeEntryResponse_ObjectType" json:"type,omitempty"`
	Oid  string                       `protobuf:"bytes,2,opt,name=oid" json:"oid,omitempty"`
	Size int64                        `protobuf:"varint,3,opt,name=size" json:"size,omitempty"`
	Mode int32                        `protobuf:"varint,4,opt,name=mode" json:"mode,omitempty"`
	Data []byte                       `protobuf:"bytes,5,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *TreeEntryResponse) Reset()                    { *m = TreeEntryResponse{} }
func (m *TreeEntryResponse) String() string            { return proto.CompactTextString(m) }
func (*TreeEntryResponse) ProtoMessage()               {}
func (*TreeEntryResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TreeEntryResponse) GetType() TreeEntryResponse_ObjectType {
	if m != nil {
		return m.Type
	}
	return TreeEntryResponse_COMMIT
}

func (m *TreeEntryResponse) GetOid() string {
	if m != nil {
		return m.Oid
	}
	return ""
}

func (m *TreeEntryResponse) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *TreeEntryResponse) GetMode() int32 {
	if m != nil {
		return m.Mode
	}
	return 0
}

func (m *TreeEntryResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CommitIsAncestorRequest)(nil), "gitaly.CommitIsAncestorRequest")
	proto.RegisterType((*CommitIsAncestorResponse)(nil), "gitaly.CommitIsAncestorResponse")
	proto.RegisterType((*TreeEntryRequest)(nil), "gitaly.TreeEntryRequest")
	proto.RegisterType((*TreeEntryResponse)(nil), "gitaly.TreeEntryResponse")
	proto.RegisterEnum("gitaly.TreeEntryResponse_ObjectType", TreeEntryResponse_ObjectType_name, TreeEntryResponse_ObjectType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Commit service

type CommitClient interface {
	CommitIsAncestor(ctx context.Context, in *CommitIsAncestorRequest, opts ...grpc.CallOption) (*CommitIsAncestorResponse, error)
	TreeEntry(ctx context.Context, in *TreeEntryRequest, opts ...grpc.CallOption) (Commit_TreeEntryClient, error)
}

type commitClient struct {
	cc *grpc.ClientConn
}

func NewCommitClient(cc *grpc.ClientConn) CommitClient {
	return &commitClient{cc}
}

func (c *commitClient) CommitIsAncestor(ctx context.Context, in *CommitIsAncestorRequest, opts ...grpc.CallOption) (*CommitIsAncestorResponse, error) {
	out := new(CommitIsAncestorResponse)
	err := grpc.Invoke(ctx, "/gitaly.Commit/CommitIsAncestor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *commitClient) TreeEntry(ctx context.Context, in *TreeEntryRequest, opts ...grpc.CallOption) (Commit_TreeEntryClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Commit_serviceDesc.Streams[0], c.cc, "/gitaly.Commit/TreeEntry", opts...)
	if err != nil {
		return nil, err
	}
	x := &commitTreeEntryClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Commit_TreeEntryClient interface {
	Recv() (*TreeEntryResponse, error)
	grpc.ClientStream
}

type commitTreeEntryClient struct {
	grpc.ClientStream
}

func (x *commitTreeEntryClient) Recv() (*TreeEntryResponse, error) {
	m := new(TreeEntryResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Commit service

type CommitServer interface {
	CommitIsAncestor(context.Context, *CommitIsAncestorRequest) (*CommitIsAncestorResponse, error)
	TreeEntry(*TreeEntryRequest, Commit_TreeEntryServer) error
}

func RegisterCommitServer(s *grpc.Server, srv CommitServer) {
	s.RegisterService(&_Commit_serviceDesc, srv)
}

func _Commit_CommitIsAncestor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitIsAncestorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).CommitIsAncestor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.Commit/CommitIsAncestor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).CommitIsAncestor(ctx, req.(*CommitIsAncestorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Commit_TreeEntry_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TreeEntryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CommitServer).TreeEntry(m, &commitTreeEntryServer{stream})
}

type Commit_TreeEntryServer interface {
	Send(*TreeEntryResponse) error
	grpc.ServerStream
}

type commitTreeEntryServer struct {
	grpc.ServerStream
}

func (x *commitTreeEntryServer) Send(m *TreeEntryResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _Commit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.Commit",
	HandlerType: (*CommitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitIsAncestor",
			Handler:    _Commit_CommitIsAncestor_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TreeEntry",
			Handler:       _Commit_TreeEntry_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "commit.proto",
}

func init() { proto.RegisterFile("commit.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 401 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x6a, 0xdc, 0x30,
	0x10, 0x86, 0x57, 0xb1, 0xd7, 0x71, 0x26, 0x4b, 0x51, 0x87, 0x42, 0x9d, 0xbd, 0xc4, 0x98, 0x1e,
	0xf6, 0x64, 0x82, 0x4b, 0xa1, 0xd7, 0x24, 0x5d, 0x8a, 0xa1, 0x61, 0x41, 0x18, 0x7a, 0x2c, 0x8e,
	0x2d, 0x1a, 0x15, 0xdb, 0x72, 0x2d, 0x25, 0xe0, 0xbe, 0x41, 0xa1, 0xef, 0xd1, 0xf7, 0xe9, 0x13,
	0x15, 0x49, 0x59, 0x67, 0xe9, 0x76, 0x4f, 0xb9, 0xfd, 0x33, 0xf3, 0x7b, 0xfc, 0xe9, 0x97, 0x60,
	0x51, 0xc9, 0xb6, 0x15, 0x3a, 0xed, 0x07, 0xa9, 0x25, 0x06, 0x5f, 0x85, 0x2e, 0x9b, 0x71, 0x49,
	0x07, 0xde, 0x4b, 0x25, 0xb4, 0x1c, 0x46, 0x37, 0x49, 0x7e, 0x12, 0x78, 0x7d, 0x6d, 0xad, 0xb9,
	0xba, 0xec, 0x2a, 0xae, 0xb4, 0x1c, 0x18, 0xff, 0x7e, 0xcf, 0x95, 0xc6, 0x0c, 0xe0, 0xc9, 0x1f,
	0x91, 0x98, 0xac, 0x4e, 0x33, 0x4c, 0xdd, 0xaa, 0x94, 0x4d, 0x13, 0xb6, 0xe3, 0xc2, 0x73, 0x38,
	0x2d, 0x1f, 0xd7, 0x7c, 0x11, 0x75, 0x74, 0x14, 0x93, 0xd5, 0x09, 0x83, 0x6d, 0x2b, 0xaf, 0xf1,
	0x0c, 0xc2, 0xea, 0x4e, 0x34, 0xb5, 0x99, 0x7a, 0x76, 0x7a, 0x6c, 0xeb, 0xbc, 0x4e, 0x2e, 0x20,
	0xda, 0x47, 0x51, 0xbd, 0xec, 0x14, 0xc7, 0x57, 0x30, 0x7f, 0x28, 0x9b, 0x7b, 0x6e, 0x31, 0x42,
	0xe6, 0x8a, 0xe4, 0x17, 0x01, 0x5a, 0x0c, 0x9c, 0xaf, 0x3b, 0x3d, 0x8c, 0xcf, 0xc1, 0x5e, 0x42,
	0x38, 0xf0, 0x07, 0xa1, 0x84, 0xec, 0x2c, 0xf3, 0x82, 0x4d, 0x35, 0x22, 0xf8, 0x7d, 0xa9, 0xef,
	0x2c, 0xed, 0x82, 0x59, 0x6d, 0x70, 0x1a, 0xd1, 0x0a, 0x1d, 0xf9, 0x31, 0x59, 0x79, 0xcc, 0x15,
	0xc9, 0x1f, 0x02, 0x2f, 0x77, 0x70, 0x1e, 0xd1, 0xdf, 0x83, 0xaf, 0xc7, 0xde, 0x91, 0xbf, 0xc8,
	0xde, 0x6c, 0x49, 0xf6, 0x8c, 0xe9, 0xe6, 0xf6, 0x1b, 0xaf, 0x74, 0x31, 0xf6, 0x9c, 0xd9, 0x2f,
	0x90, 0x82, 0x27, 0xa7, 0x10, 0x8d, 0x34, 0x2c, 0x4a, 0xfc, 0xe0, 0x96, 0xc5, 0x63, 0x56, 0x9b,
	0x5e, 0x2b, 0x6b, 0x6e, 0x51, 0xe6, 0xcc, 0x6a, 0xd3, 0xab, 0x4b, 0x5d, 0x46, 0x73, 0xc7, 0x6c,
	0x74, 0xf2, 0x0e, 0xe0, 0xe9, 0x0f, 0x08, 0x10, 0x5c, 0x6f, 0x6e, 0x6e, 0xf2, 0x82, 0xce, 0x30,
	0x04, 0xff, 0xea, 0xd3, 0xe6, 0x8a, 0x12, 0xa3, 0x0a, 0xb6, 0x5e, 0xd3, 0x23, 0x3c, 0x06, 0xaf,
	0xb8, 0xfc, 0x48, 0xbd, 0xec, 0x37, 0x81, 0xc0, 0x5d, 0x0b, 0x7e, 0x06, 0xfa, 0xef, 0x05, 0xe1,
	0xf9, 0xf6, 0x3c, 0x07, 0x5e, 0xd1, 0x32, 0x3e, 0x6c, 0x70, 0xe7, 0x4e, 0x66, 0xf8, 0x01, 0x4e,
	0xa6, 0x38, 0x30, 0xfa, 0x4f, 0x42, 0x6e, 0xd5, 0xd9, 0xc1, 0xec, 0x92, 0xd9, 0x05, 0xb9, 0x0d,
	0xec, 0x93, 0x7e, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x30, 0x6b, 0xc7, 0x5d, 0xfc, 0x02, 0x00,
	0x00,
}
