// Code generated by protoc-gen-go.
// source: gitaly.proto
// DO NOT EDIT!

/*
Package gitaly is a generated protocol buffer package.

It is generated from these files:
	gitaly.proto

It has these top-level messages:
	Boolean
	InfoRefsRequest
	InfoRefsResponse
	Repository
	PostReceiveRequest
	PostReceiveResponse
	CommitObject
	FindRefNameRequest
	RefNamesResponse
	CommitIsAncestorRequest
*/
package gitaly

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Boolean struct {
	Value bool `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
}

func (m *Boolean) Reset()                    { *m = Boolean{} }
func (m *Boolean) String() string            { return proto.CompactTextString(m) }
func (*Boolean) ProtoMessage()               {}
func (*Boolean) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Boolean) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

type InfoRefsRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
}

func (m *InfoRefsRequest) Reset()                    { *m = InfoRefsRequest{} }
func (m *InfoRefsRequest) String() string            { return proto.CompactTextString(m) }
func (*InfoRefsRequest) ProtoMessage()               {}
func (*InfoRefsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *InfoRefsRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type InfoRefsResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *InfoRefsResponse) Reset()                    { *m = InfoRefsResponse{} }
func (m *InfoRefsResponse) String() string            { return proto.CompactTextString(m) }
func (*InfoRefsResponse) ProtoMessage()               {}
func (*InfoRefsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *InfoRefsResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Repository struct {
	Path string `protobuf:"bytes,1,opt,name=path" json:"path,omitempty"`
}

func (m *Repository) Reset()                    { *m = Repository{} }
func (m *Repository) String() string            { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()               {}
func (*Repository) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Repository) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

type PostReceiveRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
}

func (m *PostReceiveRequest) Reset()                    { *m = PostReceiveRequest{} }
func (m *PostReceiveRequest) String() string            { return proto.CompactTextString(m) }
func (*PostReceiveRequest) ProtoMessage()               {}
func (*PostReceiveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PostReceiveRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type PostReceiveResponse struct {
}

func (m *PostReceiveResponse) Reset()                    { *m = PostReceiveResponse{} }
func (m *PostReceiveResponse) String() string            { return proto.CompactTextString(m) }
func (*PostReceiveResponse) ProtoMessage()               {}
func (*PostReceiveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CommitObject struct {
	// SHA1 of the commit object represented as 40 hexadecimal characters
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CommitObject) Reset()                    { *m = CommitObject{} }
func (m *CommitObject) String() string            { return proto.CompactTextString(m) }
func (*CommitObject) ProtoMessage()               {}
func (*CommitObject) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CommitObject) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type FindRefNameRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	// Require that the resulting ref contains this commit as an ancestor
	Containing *CommitObject `protobuf:"bytes,2,opt,name=containing" json:"containing,omitempty"`
	// Example prefix: "refs/heads/". Type bytes because that is the type of ref names.
	Prefix []byte `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
}

func (m *FindRefNameRequest) Reset()                    { *m = FindRefNameRequest{} }
func (m *FindRefNameRequest) String() string            { return proto.CompactTextString(m) }
func (*FindRefNameRequest) ProtoMessage()               {}
func (*FindRefNameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *FindRefNameRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *FindRefNameRequest) GetContaining() *CommitObject {
	if m != nil {
		return m.Containing
	}
	return nil
}

func (m *FindRefNameRequest) GetPrefix() []byte {
	if m != nil {
		return m.Prefix
	}
	return nil
}

type RefNamesResponse struct {
	// Example name: "refs/heads/master". Cannot assume UTF8, so the type is bytes.
	Name [][]byte `protobuf:"bytes,1,rep,name=name,proto3" json:"name,omitempty"`
}

func (m *RefNamesResponse) Reset()                    { *m = RefNamesResponse{} }
func (m *RefNamesResponse) String() string            { return proto.CompactTextString(m) }
func (*RefNamesResponse) ProtoMessage()               {}
func (*RefNamesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RefNamesResponse) GetName() [][]byte {
	if m != nil {
		return m.Name
	}
	return nil
}

type CommitIsAncestorRequest struct {
	Repository *Repository   `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
	Ancestor   *CommitObject `protobuf:"bytes,2,opt,name=ancestor" json:"ancestor,omitempty"`
	Child      *CommitObject `protobuf:"bytes,3,opt,name=child" json:"child,omitempty"`
}

func (m *CommitIsAncestorRequest) Reset()                    { *m = CommitIsAncestorRequest{} }
func (m *CommitIsAncestorRequest) String() string            { return proto.CompactTextString(m) }
func (*CommitIsAncestorRequest) ProtoMessage()               {}
func (*CommitIsAncestorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *CommitIsAncestorRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *CommitIsAncestorRequest) GetAncestor() *CommitObject {
	if m != nil {
		return m.Ancestor
	}
	return nil
}

func (m *CommitIsAncestorRequest) GetChild() *CommitObject {
	if m != nil {
		return m.Child
	}
	return nil
}

func init() {
	proto.RegisterType((*Boolean)(nil), "gitaly.Boolean")
	proto.RegisterType((*InfoRefsRequest)(nil), "gitaly.InfoRefsRequest")
	proto.RegisterType((*InfoRefsResponse)(nil), "gitaly.InfoRefsResponse")
	proto.RegisterType((*Repository)(nil), "gitaly.Repository")
	proto.RegisterType((*PostReceiveRequest)(nil), "gitaly.PostReceiveRequest")
	proto.RegisterType((*PostReceiveResponse)(nil), "gitaly.PostReceiveResponse")
	proto.RegisterType((*CommitObject)(nil), "gitaly.CommitObject")
	proto.RegisterType((*FindRefNameRequest)(nil), "gitaly.FindRefNameRequest")
	proto.RegisterType((*RefNamesResponse)(nil), "gitaly.RefNamesResponse")
	proto.RegisterType((*CommitIsAncestorRequest)(nil), "gitaly.CommitIsAncestorRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SmartHTTP service

type SmartHTTPClient interface {
	// The response body for GET /info/refs?service=git-upload-pack
	InfoRefsUploadPack(ctx context.Context, in *InfoRefsRequest, opts ...grpc.CallOption) (SmartHTTP_InfoRefsUploadPackClient, error)
	// The response body for GET /info/refs?service=git-receive-pack
	InfoRefsReceivePack(ctx context.Context, in *InfoRefsRequest, opts ...grpc.CallOption) (SmartHTTP_InfoRefsReceivePackClient, error)
}

type smartHTTPClient struct {
	cc *grpc.ClientConn
}

func NewSmartHTTPClient(cc *grpc.ClientConn) SmartHTTPClient {
	return &smartHTTPClient{cc}
}

func (c *smartHTTPClient) InfoRefsUploadPack(ctx context.Context, in *InfoRefsRequest, opts ...grpc.CallOption) (SmartHTTP_InfoRefsUploadPackClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SmartHTTP_serviceDesc.Streams[0], c.cc, "/gitaly.SmartHTTP/InfoRefsUploadPack", opts...)
	if err != nil {
		return nil, err
	}
	x := &smartHTTPInfoRefsUploadPackClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SmartHTTP_InfoRefsUploadPackClient interface {
	Recv() (*InfoRefsResponse, error)
	grpc.ClientStream
}

type smartHTTPInfoRefsUploadPackClient struct {
	grpc.ClientStream
}

func (x *smartHTTPInfoRefsUploadPackClient) Recv() (*InfoRefsResponse, error) {
	m := new(InfoRefsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *smartHTTPClient) InfoRefsReceivePack(ctx context.Context, in *InfoRefsRequest, opts ...grpc.CallOption) (SmartHTTP_InfoRefsReceivePackClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_SmartHTTP_serviceDesc.Streams[1], c.cc, "/gitaly.SmartHTTP/InfoRefsReceivePack", opts...)
	if err != nil {
		return nil, err
	}
	x := &smartHTTPInfoRefsReceivePackClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SmartHTTP_InfoRefsReceivePackClient interface {
	Recv() (*InfoRefsResponse, error)
	grpc.ClientStream
}

type smartHTTPInfoRefsReceivePackClient struct {
	grpc.ClientStream
}

func (x *smartHTTPInfoRefsReceivePackClient) Recv() (*InfoRefsResponse, error) {
	m := new(InfoRefsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for SmartHTTP service

type SmartHTTPServer interface {
	// The response body for GET /info/refs?service=git-upload-pack
	InfoRefsUploadPack(*InfoRefsRequest, SmartHTTP_InfoRefsUploadPackServer) error
	// The response body for GET /info/refs?service=git-receive-pack
	InfoRefsReceivePack(*InfoRefsRequest, SmartHTTP_InfoRefsReceivePackServer) error
}

func RegisterSmartHTTPServer(s *grpc.Server, srv SmartHTTPServer) {
	s.RegisterService(&_SmartHTTP_serviceDesc, srv)
}

func _SmartHTTP_InfoRefsUploadPack_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InfoRefsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmartHTTPServer).InfoRefsUploadPack(m, &smartHTTPInfoRefsUploadPackServer{stream})
}

type SmartHTTP_InfoRefsUploadPackServer interface {
	Send(*InfoRefsResponse) error
	grpc.ServerStream
}

type smartHTTPInfoRefsUploadPackServer struct {
	grpc.ServerStream
}

func (x *smartHTTPInfoRefsUploadPackServer) Send(m *InfoRefsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _SmartHTTP_InfoRefsReceivePack_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InfoRefsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmartHTTPServer).InfoRefsReceivePack(m, &smartHTTPInfoRefsReceivePackServer{stream})
}

type SmartHTTP_InfoRefsReceivePackServer interface {
	Send(*InfoRefsResponse) error
	grpc.ServerStream
}

type smartHTTPInfoRefsReceivePackServer struct {
	grpc.ServerStream
}

func (x *smartHTTPInfoRefsReceivePackServer) Send(m *InfoRefsResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _SmartHTTP_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.SmartHTTP",
	HandlerType: (*SmartHTTPServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "InfoRefsUploadPack",
			Handler:       _SmartHTTP_InfoRefsUploadPack_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InfoRefsReceivePack",
			Handler:       _SmartHTTP_InfoRefsReceivePack_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "gitaly.proto",
}

// Client API for Notifications service

type NotificationsClient interface {
	PostReceive(ctx context.Context, in *PostReceiveRequest, opts ...grpc.CallOption) (*PostReceiveResponse, error)
}

type notificationsClient struct {
	cc *grpc.ClientConn
}

func NewNotificationsClient(cc *grpc.ClientConn) NotificationsClient {
	return &notificationsClient{cc}
}

func (c *notificationsClient) PostReceive(ctx context.Context, in *PostReceiveRequest, opts ...grpc.CallOption) (*PostReceiveResponse, error) {
	out := new(PostReceiveResponse)
	err := grpc.Invoke(ctx, "/gitaly.Notifications/PostReceive", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Notifications service

type NotificationsServer interface {
	PostReceive(context.Context, *PostReceiveRequest) (*PostReceiveResponse, error)
}

func RegisterNotificationsServer(s *grpc.Server, srv NotificationsServer) {
	s.RegisterService(&_Notifications_serviceDesc, srv)
}

func _Notifications_PostReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PostReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NotificationsServer).PostReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.Notifications/PostReceive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NotificationsServer).PostReceive(ctx, req.(*PostReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Notifications_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.Notifications",
	HandlerType: (*NotificationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostReceive",
			Handler:    _Notifications_PostReceive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitaly.proto",
}

// Client API for Ref service

type RefClient interface {
	// Find a Ref matching the given constraints. Response may be empty.
	FindRefName(ctx context.Context, in *FindRefNameRequest, opts ...grpc.CallOption) (*RefNamesResponse, error)
}

type refClient struct {
	cc *grpc.ClientConn
}

func NewRefClient(cc *grpc.ClientConn) RefClient {
	return &refClient{cc}
}

func (c *refClient) FindRefName(ctx context.Context, in *FindRefNameRequest, opts ...grpc.CallOption) (*RefNamesResponse, error) {
	out := new(RefNamesResponse)
	err := grpc.Invoke(ctx, "/gitaly.Ref/FindRefName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ref service

type RefServer interface {
	// Find a Ref matching the given constraints. Response may be empty.
	FindRefName(context.Context, *FindRefNameRequest) (*RefNamesResponse, error)
}

func RegisterRefServer(s *grpc.Server, srv RefServer) {
	s.RegisterService(&_Ref_serviceDesc, srv)
}

func _Ref_FindRefName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRefNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RefServer).FindRefName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.Ref/FindRefName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RefServer).FindRefName(ctx, req.(*FindRefNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ref_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.Ref",
	HandlerType: (*RefServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindRefName",
			Handler:    _Ref_FindRefName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitaly.proto",
}

// Client API for Commit service

type CommitClient interface {
	CommitIsAncestor(ctx context.Context, in *CommitIsAncestorRequest, opts ...grpc.CallOption) (*Boolean, error)
}

type commitClient struct {
	cc *grpc.ClientConn
}

func NewCommitClient(cc *grpc.ClientConn) CommitClient {
	return &commitClient{cc}
}

func (c *commitClient) CommitIsAncestor(ctx context.Context, in *CommitIsAncestorRequest, opts ...grpc.CallOption) (*Boolean, error) {
	out := new(Boolean)
	err := grpc.Invoke(ctx, "/gitaly.Commit/CommitIsAncestor", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Commit service

type CommitServer interface {
	CommitIsAncestor(context.Context, *CommitIsAncestorRequest) (*Boolean, error)
}

func RegisterCommitServer(s *grpc.Server, srv CommitServer) {
	s.RegisterService(&_Commit_serviceDesc, srv)
}

func _Commit_CommitIsAncestor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitIsAncestorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommitServer).CommitIsAncestor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.Commit/CommitIsAncestor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommitServer).CommitIsAncestor(ctx, req.(*CommitIsAncestorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Commit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.Commit",
	HandlerType: (*CommitServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CommitIsAncestor",
			Handler:    _Commit_CommitIsAncestor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gitaly.proto",
}

func init() { proto.RegisterFile("gitaly.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0xc1, 0x6e, 0xd4, 0x30,
	0x10, 0xdd, 0xec, 0xd2, 0xd0, 0xce, 0x2e, 0xb4, 0x9a, 0x16, 0x1a, 0x05, 0x89, 0x56, 0x3e, 0x20,
	0xc4, 0xa1, 0xaa, 0x02, 0x3f, 0x00, 0xa8, 0xd5, 0x56, 0x54, 0x25, 0x32, 0xe5, 0xc0, 0xd1, 0x4d,
	0x9c, 0xd6, 0x90, 0xd8, 0x21, 0x76, 0x57, 0xec, 0x8f, 0xf0, 0x09, 0x5c, 0xf8, 0x49, 0x14, 0x27,
	0xd9, 0x64, 0x37, 0xc0, 0x25, 0xb7, 0x19, 0xcf, 0x9b, 0xa7, 0x37, 0x33, 0x4f, 0x86, 0xd9, 0xad,
	0x30, 0x2c, 0x5d, 0x9e, 0xe4, 0x85, 0x32, 0x0a, 0xdd, 0x2a, 0x23, 0x47, 0xf0, 0xf0, 0x9d, 0x52,
	0x29, 0x67, 0x12, 0x0f, 0x60, 0x6b, 0xc1, 0xd2, 0x7b, 0xee, 0x39, 0xc7, 0xce, 0xcb, 0x6d, 0x5a,
	0x25, 0xe4, 0x0c, 0x76, 0x2f, 0x64, 0xa2, 0x28, 0x4f, 0x34, 0xe5, 0xdf, 0xef, 0xb9, 0x36, 0x18,
	0x00, 0x14, 0x3c, 0x57, 0x5a, 0x18, 0x55, 0x2c, 0x2d, 0x7a, 0x1a, 0xe0, 0x49, 0x4d, 0x4f, 0x57,
	0x15, 0xda, 0x41, 0x91, 0x17, 0xb0, 0xd7, 0xd2, 0xe8, 0x5c, 0x49, 0xcd, 0x11, 0xe1, 0x41, 0xcc,
	0x0c, 0xb3, 0x0c, 0x33, 0x6a, 0x63, 0x72, 0x0c, 0xd0, 0x32, 0x94, 0x88, 0x9c, 0x99, 0x3b, 0x8b,
	0xd8, 0xa1, 0x36, 0x26, 0x73, 0xc0, 0x50, 0x69, 0x43, 0x79, 0xc4, 0xc5, 0x82, 0x0f, 0xd1, 0xf4,
	0x04, 0xf6, 0xd7, 0x98, 0x2a, 0x59, 0xe4, 0x39, 0xcc, 0xde, 0xab, 0x2c, 0x13, 0xe6, 0xe3, 0xcd,
	0x57, 0x1e, 0x19, 0x7c, 0x0c, 0x63, 0x11, 0xd7, 0x12, 0xc6, 0x22, 0x26, 0x3f, 0x1d, 0xc0, 0x73,
	0x21, 0x63, 0xca, 0x93, 0x2b, 0x96, 0x0d, 0x51, 0x80, 0x6f, 0x00, 0x22, 0x25, 0x0d, 0x13, 0x52,
	0xc8, 0x5b, 0x6f, 0x6c, 0x7b, 0x0e, 0x9a, 0x9e, 0xae, 0x08, 0xda, 0xc1, 0xe1, 0x53, 0x70, 0xf3,
	0x82, 0x27, 0xe2, 0x87, 0x37, 0xb1, 0x9b, 0xab, 0xb3, 0x72, 0xc7, 0xb5, 0xa6, 0xb5, 0x1d, 0x4b,
	0x96, 0x95, 0x37, 0x9d, 0x94, 0x3b, 0x2e, 0x63, 0xf2, 0xdb, 0x81, 0xc3, 0x8a, 0xfc, 0x42, 0xbf,
	0x95, 0x11, 0xd7, 0x46, 0x15, 0x43, 0xa6, 0x38, 0x85, 0x6d, 0x56, 0xd3, 0xfc, 0x77, 0x86, 0x15,
	0x0a, 0x5f, 0xc1, 0x56, 0x74, 0x27, 0xd2, 0xd8, 0x0e, 0xf0, 0x2f, 0x78, 0x05, 0x09, 0x7e, 0x39,
	0xb0, 0xf3, 0x29, 0x63, 0x85, 0x99, 0x5f, 0x5f, 0x87, 0xf8, 0x01, 0xb0, 0xf1, 0xd1, 0xe7, 0x3c,
	0x55, 0x2c, 0x0e, 0x59, 0xf4, 0x0d, 0x0f, 0x1b, 0x82, 0x0d, 0xab, 0xfa, 0x5e, 0xbf, 0x50, 0x5f,
	0x79, 0x74, 0xea, 0xe0, 0x25, 0xec, 0xb7, 0xef, 0xd6, 0x04, 0x03, 0xd8, 0x82, 0x2f, 0xf0, 0xe8,
	0x4a, 0x19, 0x91, 0x88, 0x88, 0x19, 0xa1, 0xa4, 0xc6, 0x39, 0x4c, 0x3b, 0xfe, 0x42, 0xbf, 0xe9,
	0xee, 0xdb, 0xd7, 0x7f, 0xf6, 0xd7, 0x5a, 0x43, 0x1e, 0x5c, 0xc2, 0x84, 0xf2, 0x04, 0xcf, 0x60,
	0xda, 0x31, 0x5e, 0x4b, 0xd8, 0x77, 0x63, 0x2b, 0x75, 0xd3, 0x11, 0x64, 0x14, 0x84, 0xe0, 0x56,
	0x8b, 0xc6, 0x73, 0xd8, 0xdb, 0x34, 0x02, 0x1e, 0xad, 0x1f, 0xa3, 0x67, 0x11, 0x7f, 0xb7, 0x01,
	0xd4, 0x1f, 0x07, 0x19, 0xdd, 0xb8, 0xf6, 0x53, 0x79, 0xfd, 0x27, 0x00, 0x00, 0xff, 0xff, 0xb0,
	0x68, 0x70, 0xc9, 0x64, 0x04, 0x00, 0x00,
}
