// Code generated by protoc-gen-go. DO NOT EDIT.
// source: repository.proto

package gitaly

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Repository struct {
	StorageName  string `protobuf:"bytes,2,opt,name=storage_name,json=storageName" json:"storage_name,omitempty"`
	RelativePath string `protobuf:"bytes,3,opt,name=relative_path,json=relativePath" json:"relative_path,omitempty"`
}

func (m *Repository) Reset()                    { *m = Repository{} }
func (m *Repository) String() string            { return proto.CompactTextString(m) }
func (*Repository) ProtoMessage()               {}
func (*Repository) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *Repository) GetStorageName() string {
	if m != nil {
		return m.StorageName
	}
	return ""
}

func (m *Repository) GetRelativePath() string {
	if m != nil {
		return m.RelativePath
	}
	return ""
}

type RepositoryExistsRequest struct {
	Repository *Repository `protobuf:"bytes,1,opt,name=repository" json:"repository,omitempty"`
}

func (m *RepositoryExistsRequest) Reset()                    { *m = RepositoryExistsRequest{} }
func (m *RepositoryExistsRequest) String() string            { return proto.CompactTextString(m) }
func (*RepositoryExistsRequest) ProtoMessage()               {}
func (*RepositoryExistsRequest) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *RepositoryExistsRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type RepositoryExistsResponse struct {
	Exists bool `protobuf:"varint,1,opt,name=exists" json:"exists,omitempty"`
}

func (m *RepositoryExistsResponse) Reset()                    { *m = RepositoryExistsResponse{} }
func (m *RepositoryExistsResponse) String() string            { return proto.CompactTextString(m) }
func (*RepositoryExistsResponse) ProtoMessage()               {}
func (*RepositoryExistsResponse) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *RepositoryExistsResponse) GetExists() bool {
	if m != nil {
		return m.Exists
	}
	return false
}

func init() {
	proto.RegisterType((*Repository)(nil), "gitaly.Repository")
	proto.RegisterType((*RepositoryExistsRequest)(nil), "gitaly.RepositoryExistsRequest")
	proto.RegisterType((*RepositoryExistsResponse)(nil), "gitaly.RepositoryExistsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for RepositoryService service

type RepositoryServiceClient interface {
	Exists(ctx context.Context, in *RepositoryExistsRequest, opts ...grpc.CallOption) (*RepositoryExistsResponse, error)
}

type repositoryServiceClient struct {
	cc *grpc.ClientConn
}

func NewRepositoryServiceClient(cc *grpc.ClientConn) RepositoryServiceClient {
	return &repositoryServiceClient{cc}
}

func (c *repositoryServiceClient) Exists(ctx context.Context, in *RepositoryExistsRequest, opts ...grpc.CallOption) (*RepositoryExistsResponse, error) {
	out := new(RepositoryExistsResponse)
	err := grpc.Invoke(ctx, "/gitaly.RepositoryService/Exists", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for RepositoryService service

type RepositoryServiceServer interface {
	Exists(context.Context, *RepositoryExistsRequest) (*RepositoryExistsResponse, error)
}

func RegisterRepositoryServiceServer(s *grpc.Server, srv RepositoryServiceServer) {
	s.RegisterService(&_RepositoryService_serviceDesc, srv)
}

func _RepositoryService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RepositoryExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RepositoryServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.RepositoryService/Exists",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RepositoryServiceServer).Exists(ctx, req.(*RepositoryExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RepositoryService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.RepositoryService",
	HandlerType: (*RepositoryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Exists",
			Handler:    _RepositoryService_Exists_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "repository.proto",
}

func init() { proto.RegisterFile("repository.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 224 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x50, 0x4d, 0x4e, 0x42, 0x31,
	0x10, 0xb6, 0x48, 0x1a, 0x1c, 0x30, 0xc1, 0x59, 0x68, 0xe3, 0xc6, 0x67, 0xdd, 0xb0, 0x7a, 0x8b,
	0x7a, 0x06, 0x37, 0x26, 0x18, 0x53, 0x0f, 0x80, 0xc5, 0x4c, 0xa0, 0x09, 0xd0, 0xda, 0x8e, 0x44,
	0x6e, 0x6f, 0xec, 0x43, 0xab, 0x21, 0x2c, 0xe7, 0xfb, 0xcf, 0xc0, 0x38, 0x51, 0x0c, 0xd9, 0x73,
	0x48, 0xbb, 0x36, 0xa6, 0xc0, 0x01, 0xe5, 0xc2, 0xb3, 0x5b, 0xed, 0xf4, 0x2b, 0x80, 0xfd, 0xe5,
	0xf0, 0x16, 0x46, 0x99, 0x43, 0x72, 0x0b, 0x9a, 0x6d, 0xdc, 0x9a, 0x54, 0xaf, 0x11, 0x93, 0x33,
	0x3b, 0xdc, 0x63, 0x4f, 0x6e, 0x4d, 0x78, 0x07, 0xe7, 0x89, 0x56, 0x8e, 0xfd, 0x96, 0x66, 0xd1,
	0xf1, 0x52, 0x9d, 0x16, 0xcd, 0xe8, 0x07, 0x7c, 0x76, 0xbc, 0x7c, 0xec, 0x0f, 0xc4, 0xb8, 0x67,
	0xfb, 0xdf, 0xbc, 0x9e, 0xc2, 0x55, 0x6d, 0x78, 0xf8, 0xf4, 0x99, 0xb3, 0xa5, 0xf7, 0x0f, 0xca,
	0x8c, 0x06, 0xa0, 0x0e, 0x53, 0xa2, 0x11, 0x93, 0xa1, 0xc1, 0xb6, 0x5b, 0xd6, 0x56, 0x93, 0xfd,
	0xa3, 0xd2, 0x06, 0xd4, 0x61, 0x5c, 0x8e, 0x61, 0x93, 0x09, 0x2f, 0x41, 0x52, 0x41, 0x4a, 0xd6,
	0xc0, 0xee, 0x2f, 0x33, 0x87, 0x8b, 0xea, 0x79, 0xa1, 0xb4, 0xf5, 0x6f, 0x84, 0x53, 0x90, 0x9d,
	0x1d, 0x6f, 0x0e, 0x2b, 0xff, 0xed, 0xbc, 0x6e, 0x8e, 0x0b, 0xba, 0x66, 0x7d, 0x32, 0x97, 0xe5,
	0xaf, 0xf7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x6e, 0x3d, 0x0f, 0x6b, 0x01, 0x00, 0x00,
}
