// Code generated by protoc-gen-go. DO NOT EDIT.
// source: objectpool.proto

package gitalypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Creates an object pool from the repository. The client is responsible for
// joining this pool later with this repository.
type CreateObjectPoolRequest struct {
	ObjectPool           *ObjectPool `protobuf:"bytes,1,opt,name=object_pool,json=objectPool,proto3" json:"object_pool,omitempty"`
	Origin               *Repository `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *CreateObjectPoolRequest) Reset()         { *m = CreateObjectPoolRequest{} }
func (m *CreateObjectPoolRequest) String() string { return proto.CompactTextString(m) }
func (*CreateObjectPoolRequest) ProtoMessage()    {}
func (*CreateObjectPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{0}
}
func (m *CreateObjectPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateObjectPoolRequest.Unmarshal(m, b)
}
func (m *CreateObjectPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateObjectPoolRequest.Marshal(b, m, deterministic)
}
func (dst *CreateObjectPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateObjectPoolRequest.Merge(dst, src)
}
func (m *CreateObjectPoolRequest) XXX_Size() int {
	return xxx_messageInfo_CreateObjectPoolRequest.Size(m)
}
func (m *CreateObjectPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateObjectPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateObjectPoolRequest proto.InternalMessageInfo

func (m *CreateObjectPoolRequest) GetObjectPool() *ObjectPool {
	if m != nil {
		return m.ObjectPool
	}
	return nil
}

func (m *CreateObjectPoolRequest) GetOrigin() *Repository {
	if m != nil {
		return m.Origin
	}
	return nil
}

type CreateObjectPoolResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateObjectPoolResponse) Reset()         { *m = CreateObjectPoolResponse{} }
func (m *CreateObjectPoolResponse) String() string { return proto.CompactTextString(m) }
func (*CreateObjectPoolResponse) ProtoMessage()    {}
func (*CreateObjectPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{1}
}
func (m *CreateObjectPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateObjectPoolResponse.Unmarshal(m, b)
}
func (m *CreateObjectPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateObjectPoolResponse.Marshal(b, m, deterministic)
}
func (dst *CreateObjectPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateObjectPoolResponse.Merge(dst, src)
}
func (m *CreateObjectPoolResponse) XXX_Size() int {
	return xxx_messageInfo_CreateObjectPoolResponse.Size(m)
}
func (m *CreateObjectPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateObjectPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateObjectPoolResponse proto.InternalMessageInfo

// Removes the directory from disk, caller is responsible for leaving the object
// pool before calling this RPC
type DeleteObjectPoolRequest struct {
	ObjectPool           *ObjectPool `protobuf:"bytes,1,opt,name=object_pool,json=objectPool,proto3" json:"object_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DeleteObjectPoolRequest) Reset()         { *m = DeleteObjectPoolRequest{} }
func (m *DeleteObjectPoolRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectPoolRequest) ProtoMessage()    {}
func (*DeleteObjectPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{2}
}
func (m *DeleteObjectPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectPoolRequest.Unmarshal(m, b)
}
func (m *DeleteObjectPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectPoolRequest.Marshal(b, m, deterministic)
}
func (dst *DeleteObjectPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectPoolRequest.Merge(dst, src)
}
func (m *DeleteObjectPoolRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectPoolRequest.Size(m)
}
func (m *DeleteObjectPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectPoolRequest proto.InternalMessageInfo

func (m *DeleteObjectPoolRequest) GetObjectPool() *ObjectPool {
	if m != nil {
		return m.ObjectPool
	}
	return nil
}

type DeleteObjectPoolResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteObjectPoolResponse) Reset()         { *m = DeleteObjectPoolResponse{} }
func (m *DeleteObjectPoolResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteObjectPoolResponse) ProtoMessage()    {}
func (*DeleteObjectPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{3}
}
func (m *DeleteObjectPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteObjectPoolResponse.Unmarshal(m, b)
}
func (m *DeleteObjectPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteObjectPoolResponse.Marshal(b, m, deterministic)
}
func (dst *DeleteObjectPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteObjectPoolResponse.Merge(dst, src)
}
func (m *DeleteObjectPoolResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteObjectPoolResponse.Size(m)
}
func (m *DeleteObjectPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteObjectPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteObjectPoolResponse proto.InternalMessageInfo

type LinkRepositoryToObjectPoolRequest struct {
	ObjectPool           *ObjectPool `protobuf:"bytes,1,opt,name=object_pool,json=objectPool,proto3" json:"object_pool,omitempty"`
	Repository           *Repository `protobuf:"bytes,2,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LinkRepositoryToObjectPoolRequest) Reset()         { *m = LinkRepositoryToObjectPoolRequest{} }
func (m *LinkRepositoryToObjectPoolRequest) String() string { return proto.CompactTextString(m) }
func (*LinkRepositoryToObjectPoolRequest) ProtoMessage()    {}
func (*LinkRepositoryToObjectPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{4}
}
func (m *LinkRepositoryToObjectPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkRepositoryToObjectPoolRequest.Unmarshal(m, b)
}
func (m *LinkRepositoryToObjectPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkRepositoryToObjectPoolRequest.Marshal(b, m, deterministic)
}
func (dst *LinkRepositoryToObjectPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkRepositoryToObjectPoolRequest.Merge(dst, src)
}
func (m *LinkRepositoryToObjectPoolRequest) XXX_Size() int {
	return xxx_messageInfo_LinkRepositoryToObjectPoolRequest.Size(m)
}
func (m *LinkRepositoryToObjectPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkRepositoryToObjectPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LinkRepositoryToObjectPoolRequest proto.InternalMessageInfo

func (m *LinkRepositoryToObjectPoolRequest) GetObjectPool() *ObjectPool {
	if m != nil {
		return m.ObjectPool
	}
	return nil
}

func (m *LinkRepositoryToObjectPoolRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type LinkRepositoryToObjectPoolResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LinkRepositoryToObjectPoolResponse) Reset()         { *m = LinkRepositoryToObjectPoolResponse{} }
func (m *LinkRepositoryToObjectPoolResponse) String() string { return proto.CompactTextString(m) }
func (*LinkRepositoryToObjectPoolResponse) ProtoMessage()    {}
func (*LinkRepositoryToObjectPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{5}
}
func (m *LinkRepositoryToObjectPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LinkRepositoryToObjectPoolResponse.Unmarshal(m, b)
}
func (m *LinkRepositoryToObjectPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LinkRepositoryToObjectPoolResponse.Marshal(b, m, deterministic)
}
func (dst *LinkRepositoryToObjectPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LinkRepositoryToObjectPoolResponse.Merge(dst, src)
}
func (m *LinkRepositoryToObjectPoolResponse) XXX_Size() int {
	return xxx_messageInfo_LinkRepositoryToObjectPoolResponse.Size(m)
}
func (m *LinkRepositoryToObjectPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LinkRepositoryToObjectPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LinkRepositoryToObjectPoolResponse proto.InternalMessageInfo

// This RPC doesn't require the ObjectPool as it will remove the alternates file
// from the pool participant. The caller is responsible no data loss occurs.
type UnlinkRepositoryFromObjectPoolRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	ObjectPool           *ObjectPool `protobuf:"bytes,2,opt,name=object_pool,json=objectPool,proto3" json:"object_pool,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *UnlinkRepositoryFromObjectPoolRequest) Reset()         { *m = UnlinkRepositoryFromObjectPoolRequest{} }
func (m *UnlinkRepositoryFromObjectPoolRequest) String() string { return proto.CompactTextString(m) }
func (*UnlinkRepositoryFromObjectPoolRequest) ProtoMessage()    {}
func (*UnlinkRepositoryFromObjectPoolRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{6}
}
func (m *UnlinkRepositoryFromObjectPoolRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlinkRepositoryFromObjectPoolRequest.Unmarshal(m, b)
}
func (m *UnlinkRepositoryFromObjectPoolRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlinkRepositoryFromObjectPoolRequest.Marshal(b, m, deterministic)
}
func (dst *UnlinkRepositoryFromObjectPoolRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlinkRepositoryFromObjectPoolRequest.Merge(dst, src)
}
func (m *UnlinkRepositoryFromObjectPoolRequest) XXX_Size() int {
	return xxx_messageInfo_UnlinkRepositoryFromObjectPoolRequest.Size(m)
}
func (m *UnlinkRepositoryFromObjectPoolRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlinkRepositoryFromObjectPoolRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnlinkRepositoryFromObjectPoolRequest proto.InternalMessageInfo

func (m *UnlinkRepositoryFromObjectPoolRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

func (m *UnlinkRepositoryFromObjectPoolRequest) GetObjectPool() *ObjectPool {
	if m != nil {
		return m.ObjectPool
	}
	return nil
}

type UnlinkRepositoryFromObjectPoolResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnlinkRepositoryFromObjectPoolResponse) Reset() {
	*m = UnlinkRepositoryFromObjectPoolResponse{}
}
func (m *UnlinkRepositoryFromObjectPoolResponse) String() string { return proto.CompactTextString(m) }
func (*UnlinkRepositoryFromObjectPoolResponse) ProtoMessage()    {}
func (*UnlinkRepositoryFromObjectPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{7}
}
func (m *UnlinkRepositoryFromObjectPoolResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnlinkRepositoryFromObjectPoolResponse.Unmarshal(m, b)
}
func (m *UnlinkRepositoryFromObjectPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnlinkRepositoryFromObjectPoolResponse.Marshal(b, m, deterministic)
}
func (dst *UnlinkRepositoryFromObjectPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnlinkRepositoryFromObjectPoolResponse.Merge(dst, src)
}
func (m *UnlinkRepositoryFromObjectPoolResponse) XXX_Size() int {
	return xxx_messageInfo_UnlinkRepositoryFromObjectPoolResponse.Size(m)
}
func (m *UnlinkRepositoryFromObjectPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnlinkRepositoryFromObjectPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnlinkRepositoryFromObjectPoolResponse proto.InternalMessageInfo

type ReduplicateRepositoryRequest struct {
	Repository           *Repository `protobuf:"bytes,1,opt,name=repository,proto3" json:"repository,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ReduplicateRepositoryRequest) Reset()         { *m = ReduplicateRepositoryRequest{} }
func (m *ReduplicateRepositoryRequest) String() string { return proto.CompactTextString(m) }
func (*ReduplicateRepositoryRequest) ProtoMessage()    {}
func (*ReduplicateRepositoryRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{8}
}
func (m *ReduplicateRepositoryRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduplicateRepositoryRequest.Unmarshal(m, b)
}
func (m *ReduplicateRepositoryRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduplicateRepositoryRequest.Marshal(b, m, deterministic)
}
func (dst *ReduplicateRepositoryRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduplicateRepositoryRequest.Merge(dst, src)
}
func (m *ReduplicateRepositoryRequest) XXX_Size() int {
	return xxx_messageInfo_ReduplicateRepositoryRequest.Size(m)
}
func (m *ReduplicateRepositoryRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduplicateRepositoryRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReduplicateRepositoryRequest proto.InternalMessageInfo

func (m *ReduplicateRepositoryRequest) GetRepository() *Repository {
	if m != nil {
		return m.Repository
	}
	return nil
}

type ReduplicateRepositoryResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReduplicateRepositoryResponse) Reset()         { *m = ReduplicateRepositoryResponse{} }
func (m *ReduplicateRepositoryResponse) String() string { return proto.CompactTextString(m) }
func (*ReduplicateRepositoryResponse) ProtoMessage()    {}
func (*ReduplicateRepositoryResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_objectpool_5d31e899201586b7, []int{9}
}
func (m *ReduplicateRepositoryResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReduplicateRepositoryResponse.Unmarshal(m, b)
}
func (m *ReduplicateRepositoryResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReduplicateRepositoryResponse.Marshal(b, m, deterministic)
}
func (dst *ReduplicateRepositoryResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReduplicateRepositoryResponse.Merge(dst, src)
}
func (m *ReduplicateRepositoryResponse) XXX_Size() int {
	return xxx_messageInfo_ReduplicateRepositoryResponse.Size(m)
}
func (m *ReduplicateRepositoryResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReduplicateRepositoryResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReduplicateRepositoryResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*CreateObjectPoolRequest)(nil), "gitaly.CreateObjectPoolRequest")
	proto.RegisterType((*CreateObjectPoolResponse)(nil), "gitaly.CreateObjectPoolResponse")
	proto.RegisterType((*DeleteObjectPoolRequest)(nil), "gitaly.DeleteObjectPoolRequest")
	proto.RegisterType((*DeleteObjectPoolResponse)(nil), "gitaly.DeleteObjectPoolResponse")
	proto.RegisterType((*LinkRepositoryToObjectPoolRequest)(nil), "gitaly.LinkRepositoryToObjectPoolRequest")
	proto.RegisterType((*LinkRepositoryToObjectPoolResponse)(nil), "gitaly.LinkRepositoryToObjectPoolResponse")
	proto.RegisterType((*UnlinkRepositoryFromObjectPoolRequest)(nil), "gitaly.UnlinkRepositoryFromObjectPoolRequest")
	proto.RegisterType((*UnlinkRepositoryFromObjectPoolResponse)(nil), "gitaly.UnlinkRepositoryFromObjectPoolResponse")
	proto.RegisterType((*ReduplicateRepositoryRequest)(nil), "gitaly.ReduplicateRepositoryRequest")
	proto.RegisterType((*ReduplicateRepositoryResponse)(nil), "gitaly.ReduplicateRepositoryResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ObjectPoolServiceClient is the client API for ObjectPoolService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ObjectPoolServiceClient interface {
	CreateObjectPool(ctx context.Context, in *CreateObjectPoolRequest, opts ...grpc.CallOption) (*CreateObjectPoolResponse, error)
	DeleteObjectPool(ctx context.Context, in *DeleteObjectPoolRequest, opts ...grpc.CallOption) (*DeleteObjectPoolResponse, error)
	// Repositories are assumed to be stored on the same disk
	LinkRepositoryToObjectPool(ctx context.Context, in *LinkRepositoryToObjectPoolRequest, opts ...grpc.CallOption) (*LinkRepositoryToObjectPoolResponse, error)
	UnlinkRepositoryFromObjectPool(ctx context.Context, in *UnlinkRepositoryFromObjectPoolRequest, opts ...grpc.CallOption) (*UnlinkRepositoryFromObjectPoolResponse, error)
	ReduplicateRepository(ctx context.Context, in *ReduplicateRepositoryRequest, opts ...grpc.CallOption) (*ReduplicateRepositoryResponse, error)
}

type objectPoolServiceClient struct {
	cc *grpc.ClientConn
}

func NewObjectPoolServiceClient(cc *grpc.ClientConn) ObjectPoolServiceClient {
	return &objectPoolServiceClient{cc}
}

func (c *objectPoolServiceClient) CreateObjectPool(ctx context.Context, in *CreateObjectPoolRequest, opts ...grpc.CallOption) (*CreateObjectPoolResponse, error) {
	out := new(CreateObjectPoolResponse)
	err := c.cc.Invoke(ctx, "/gitaly.ObjectPoolService/CreateObjectPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectPoolServiceClient) DeleteObjectPool(ctx context.Context, in *DeleteObjectPoolRequest, opts ...grpc.CallOption) (*DeleteObjectPoolResponse, error) {
	out := new(DeleteObjectPoolResponse)
	err := c.cc.Invoke(ctx, "/gitaly.ObjectPoolService/DeleteObjectPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectPoolServiceClient) LinkRepositoryToObjectPool(ctx context.Context, in *LinkRepositoryToObjectPoolRequest, opts ...grpc.CallOption) (*LinkRepositoryToObjectPoolResponse, error) {
	out := new(LinkRepositoryToObjectPoolResponse)
	err := c.cc.Invoke(ctx, "/gitaly.ObjectPoolService/LinkRepositoryToObjectPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectPoolServiceClient) UnlinkRepositoryFromObjectPool(ctx context.Context, in *UnlinkRepositoryFromObjectPoolRequest, opts ...grpc.CallOption) (*UnlinkRepositoryFromObjectPoolResponse, error) {
	out := new(UnlinkRepositoryFromObjectPoolResponse)
	err := c.cc.Invoke(ctx, "/gitaly.ObjectPoolService/UnlinkRepositoryFromObjectPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectPoolServiceClient) ReduplicateRepository(ctx context.Context, in *ReduplicateRepositoryRequest, opts ...grpc.CallOption) (*ReduplicateRepositoryResponse, error) {
	out := new(ReduplicateRepositoryResponse)
	err := c.cc.Invoke(ctx, "/gitaly.ObjectPoolService/ReduplicateRepository", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ObjectPoolServiceServer is the server API for ObjectPoolService service.
type ObjectPoolServiceServer interface {
	CreateObjectPool(context.Context, *CreateObjectPoolRequest) (*CreateObjectPoolResponse, error)
	DeleteObjectPool(context.Context, *DeleteObjectPoolRequest) (*DeleteObjectPoolResponse, error)
	// Repositories are assumed to be stored on the same disk
	LinkRepositoryToObjectPool(context.Context, *LinkRepositoryToObjectPoolRequest) (*LinkRepositoryToObjectPoolResponse, error)
	UnlinkRepositoryFromObjectPool(context.Context, *UnlinkRepositoryFromObjectPoolRequest) (*UnlinkRepositoryFromObjectPoolResponse, error)
	ReduplicateRepository(context.Context, *ReduplicateRepositoryRequest) (*ReduplicateRepositoryResponse, error)
}

func RegisterObjectPoolServiceServer(s *grpc.Server, srv ObjectPoolServiceServer) {
	s.RegisterService(&_ObjectPoolService_serviceDesc, srv)
}

func _ObjectPoolService_CreateObjectPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectPoolServiceServer).CreateObjectPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.ObjectPoolService/CreateObjectPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectPoolServiceServer).CreateObjectPool(ctx, req.(*CreateObjectPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectPoolService_DeleteObjectPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectPoolServiceServer).DeleteObjectPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.ObjectPoolService/DeleteObjectPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectPoolServiceServer).DeleteObjectPool(ctx, req.(*DeleteObjectPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectPoolService_LinkRepositoryToObjectPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LinkRepositoryToObjectPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectPoolServiceServer).LinkRepositoryToObjectPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.ObjectPoolService/LinkRepositoryToObjectPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectPoolServiceServer).LinkRepositoryToObjectPool(ctx, req.(*LinkRepositoryToObjectPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectPoolService_UnlinkRepositoryFromObjectPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlinkRepositoryFromObjectPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectPoolServiceServer).UnlinkRepositoryFromObjectPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.ObjectPoolService/UnlinkRepositoryFromObjectPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectPoolServiceServer).UnlinkRepositoryFromObjectPool(ctx, req.(*UnlinkRepositoryFromObjectPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ObjectPoolService_ReduplicateRepository_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduplicateRepositoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ObjectPoolServiceServer).ReduplicateRepository(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.ObjectPoolService/ReduplicateRepository",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ObjectPoolServiceServer).ReduplicateRepository(ctx, req.(*ReduplicateRepositoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ObjectPoolService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.ObjectPoolService",
	HandlerType: (*ObjectPoolServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObjectPool",
			Handler:    _ObjectPoolService_CreateObjectPool_Handler,
		},
		{
			MethodName: "DeleteObjectPool",
			Handler:    _ObjectPoolService_DeleteObjectPool_Handler,
		},
		{
			MethodName: "LinkRepositoryToObjectPool",
			Handler:    _ObjectPoolService_LinkRepositoryToObjectPool_Handler,
		},
		{
			MethodName: "UnlinkRepositoryFromObjectPool",
			Handler:    _ObjectPoolService_UnlinkRepositoryFromObjectPool_Handler,
		},
		{
			MethodName: "ReduplicateRepository",
			Handler:    _ObjectPoolService_ReduplicateRepository_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "objectpool.proto",
}

func init() { proto.RegisterFile("objectpool.proto", fileDescriptor_objectpool_5d31e899201586b7) }

var fileDescriptor_objectpool_5d31e899201586b7 = []byte{
	// 385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0x29, 0x31, 0x8d, 0xb9, 0xb8, 0xc0, 0x49, 0x0c, 0xa4, 0x51, 0xc1, 0x06, 0x0c, 0x92,
	0xd8, 0x05, 0xec, 0xdc, 0x6a, 0x5c, 0x99, 0x68, 0xea, 0x5f, 0xe2, 0xc6, 0x14, 0xb8, 0x62, 0xb5,
	0xf6, 0xd6, 0xe9, 0x60, 0xc2, 0x52, 0x9f, 0xc1, 0x44, 0x1f, 0xc1, 0xe7, 0xf3, 0x09, 0x0c, 0xf4,
	0x17, 0x70, 0xa0, 0x1a, 0x76, 0x4d, 0x73, 0x7a, 0xce, 0x77, 0xef, 0x9c, 0x0e, 0x14, 0xa9, 0xf3,
	0x80, 0x5d, 0xe1, 0x11, 0x39, 0x86, 0xc7, 0x49, 0x10, 0x53, 0xfb, 0xb6, 0xb0, 0x9c, 0xa1, 0xb6,
	0xe6, 0xdf, 0x5b, 0x1c, 0x7b, 0xc1, 0x5b, 0xfd, 0x4d, 0x81, 0xd2, 0x21, 0x47, 0x4b, 0xe0, 0xe9,
	0xf8, 0x83, 0x33, 0x22, 0xc7, 0xc4, 0xe7, 0x01, 0xfa, 0x82, 0xb5, 0xa1, 0x10, 0xb8, 0xdc, 0x8e,
	0x6c, 0xca, 0x4a, 0x55, 0x69, 0x14, 0x5a, 0xcc, 0x08, 0x7c, 0x8c, 0x94, 0x1e, 0x28, 0x7e, 0x66,
	0x4d, 0x50, 0x89, 0xdb, 0x7d, 0xdb, 0x2d, 0xe7, 0x27, 0xf5, 0x26, 0x7a, 0xe4, 0xdb, 0x82, 0xf8,
	0xd0, 0x0c, 0x15, 0x07, 0xea, 0xf7, 0x47, 0x23, 0xbf, 0x9a, 0xd3, 0x35, 0x28, 0xcf, 0x32, 0xf8,
	0x1e, 0xb9, 0x3e, 0xea, 0x57, 0x50, 0x3a, 0x42, 0x07, 0x97, 0xc5, 0x97, 0xce, 0x9c, 0xf5, 0x0d,
	0x33, 0xdf, 0x15, 0xd8, 0x39, 0xb1, 0xdd, 0xc7, 0x04, 0xf9, 0x82, 0x96, 0xb4, 0x9e, 0x16, 0x00,
	0x8f, 0x5d, 0xe7, 0xac, 0x28, 0xa5, 0x8a, 0x91, 0x6b, 0xa0, 0xcf, 0xa3, 0x0a, 0xe1, 0x3f, 0x15,
	0xa8, 0x5f, 0xba, 0xce, 0x84, 0xf0, 0x98, 0xd3, 0xd3, 0xec, 0x00, 0x93, 0x2c, 0x4a, 0x16, 0x96,
	0xe9, 0xa1, 0xf3, 0x7f, 0xda, 0x79, 0x03, 0x76, 0x17, 0x91, 0x85, 0x43, 0xdc, 0xc0, 0xa6, 0x89,
	0xbd, 0x81, 0xe7, 0xd8, 0x5d, 0x4b, 0x60, 0x8a, 0xe5, 0xff, 0xe8, 0x31, 0x45, 0x05, 0xb6, 0x24,
	0xde, 0x41, 0x78, 0xeb, 0x6b, 0x05, 0xd6, 0x13, 0xa6, 0x73, 0xe4, 0x2f, 0x76, 0x17, 0xd9, 0x35,
	0x14, 0xa7, 0x4b, 0xca, 0x2a, 0x51, 0xa4, 0xe4, 0x17, 0xd2, 0xaa, 0x72, 0x41, 0x38, 0x69, 0x6e,
	0x64, 0x3c, 0xdd, 0xc4, 0xc4, 0x58, 0xd2, 0xfd, 0xc4, 0x58, 0x5a, 0xe2, 0x1c, 0x1b, 0x80, 0x26,
	0xef, 0x0b, 0xdb, 0x8b, 0x1c, 0x16, 0x36, 0x5d, 0x6b, 0x66, 0x91, 0xc6, 0xb1, 0xaf, 0x0a, 0x6c,
	0xcf, 0x3f, 0x66, 0xb6, 0x1f, 0x19, 0x66, 0x2a, 0xaa, 0x66, 0x64, 0x95, 0xc7, 0x0c, 0x77, 0xb0,
	0xf1, 0xeb, 0x19, 0xb3, 0x5a, 0x52, 0x12, 0x79, 0xbd, 0xb4, 0xfa, 0x02, 0x55, 0x94, 0xd3, 0x51,
	0xc7, 0xb7, 0x68, 0xfb, 0x27, 0x00, 0x00, 0xff, 0xff, 0x54, 0x4b, 0x40, 0xcc, 0x6f, 0x05, 0x00,
	0x00,
}
