// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package gitalypb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ServerInfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfoRequest) Reset()         { *m = ServerInfoRequest{} }
func (m *ServerInfoRequest) String() string { return proto.CompactTextString(m) }
func (*ServerInfoRequest) ProtoMessage()    {}
func (*ServerInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5af9ff290d7e433b, []int{0}
}
func (m *ServerInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoRequest.Unmarshal(m, b)
}
func (m *ServerInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoRequest.Marshal(b, m, deterministic)
}
func (dst *ServerInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoRequest.Merge(dst, src)
}
func (m *ServerInfoRequest) XXX_Size() int {
	return xxx_messageInfo_ServerInfoRequest.Size(m)
}
func (m *ServerInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoRequest proto.InternalMessageInfo

type ServerInfoResponse struct {
	ServerVersion        string                              `protobuf:"bytes,1,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	GitVersion           string                              `protobuf:"bytes,2,opt,name=git_version,json=gitVersion,proto3" json:"git_version,omitempty"`
	StorageStatuses      []*ServerInfoResponse_StorageStatus `protobuf:"bytes,3,rep,name=storage_statuses,json=storageStatuses,proto3" json:"storage_statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *ServerInfoResponse) Reset()         { *m = ServerInfoResponse{} }
func (m *ServerInfoResponse) String() string { return proto.CompactTextString(m) }
func (*ServerInfoResponse) ProtoMessage()    {}
func (*ServerInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5af9ff290d7e433b, []int{1}
}
func (m *ServerInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoResponse.Unmarshal(m, b)
}
func (m *ServerInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoResponse.Marshal(b, m, deterministic)
}
func (dst *ServerInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoResponse.Merge(dst, src)
}
func (m *ServerInfoResponse) XXX_Size() int {
	return xxx_messageInfo_ServerInfoResponse.Size(m)
}
func (m *ServerInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoResponse proto.InternalMessageInfo

func (m *ServerInfoResponse) GetServerVersion() string {
	if m != nil {
		return m.ServerVersion
	}
	return ""
}

func (m *ServerInfoResponse) GetGitVersion() string {
	if m != nil {
		return m.GitVersion
	}
	return ""
}

func (m *ServerInfoResponse) GetStorageStatuses() []*ServerInfoResponse_StorageStatus {
	if m != nil {
		return m.StorageStatuses
	}
	return nil
}

type ServerInfoResponse_StorageStatus struct {
	StorageName          string   `protobuf:"bytes,1,opt,name=storage_name,json=storageName,proto3" json:"storage_name,omitempty"`
	Readable             bool     `protobuf:"varint,2,opt,name=readable,proto3" json:"readable,omitempty"`
	Writeable            bool     `protobuf:"varint,3,opt,name=writeable,proto3" json:"writeable,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfoResponse_StorageStatus) Reset()         { *m = ServerInfoResponse_StorageStatus{} }
func (m *ServerInfoResponse_StorageStatus) String() string { return proto.CompactTextString(m) }
func (*ServerInfoResponse_StorageStatus) ProtoMessage()    {}
func (*ServerInfoResponse_StorageStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_server_5af9ff290d7e433b, []int{1, 0}
}
func (m *ServerInfoResponse_StorageStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfoResponse_StorageStatus.Unmarshal(m, b)
}
func (m *ServerInfoResponse_StorageStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfoResponse_StorageStatus.Marshal(b, m, deterministic)
}
func (dst *ServerInfoResponse_StorageStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfoResponse_StorageStatus.Merge(dst, src)
}
func (m *ServerInfoResponse_StorageStatus) XXX_Size() int {
	return xxx_messageInfo_ServerInfoResponse_StorageStatus.Size(m)
}
func (m *ServerInfoResponse_StorageStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfoResponse_StorageStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfoResponse_StorageStatus proto.InternalMessageInfo

func (m *ServerInfoResponse_StorageStatus) GetStorageName() string {
	if m != nil {
		return m.StorageName
	}
	return ""
}

func (m *ServerInfoResponse_StorageStatus) GetReadable() bool {
	if m != nil {
		return m.Readable
	}
	return false
}

func (m *ServerInfoResponse_StorageStatus) GetWriteable() bool {
	if m != nil {
		return m.Writeable
	}
	return false
}

func init() {
	proto.RegisterType((*ServerInfoRequest)(nil), "gitaly.ServerInfoRequest")
	proto.RegisterType((*ServerInfoResponse)(nil), "gitaly.ServerInfoResponse")
	proto.RegisterType((*ServerInfoResponse_StorageStatus)(nil), "gitaly.ServerInfoResponse.StorageStatus")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ServerServiceClient is the client API for ServerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ServerServiceClient interface {
	ServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error)
}

type serverServiceClient struct {
	cc *grpc.ClientConn
}

func NewServerServiceClient(cc *grpc.ClientConn) ServerServiceClient {
	return &serverServiceClient{cc}
}

func (c *serverServiceClient) ServerInfo(ctx context.Context, in *ServerInfoRequest, opts ...grpc.CallOption) (*ServerInfoResponse, error) {
	out := new(ServerInfoResponse)
	err := c.cc.Invoke(ctx, "/gitaly.ServerService/ServerInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServiceServer is the server API for ServerService service.
type ServerServiceServer interface {
	ServerInfo(context.Context, *ServerInfoRequest) (*ServerInfoResponse, error)
}

func RegisterServerServiceServer(s *grpc.Server, srv ServerServiceServer) {
	s.RegisterService(&_ServerService_serviceDesc, srv)
}

func _ServerService_ServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServiceServer).ServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gitaly.ServerService/ServerInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServiceServer).ServerInfo(ctx, req.(*ServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ServerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gitaly.ServerService",
	HandlerType: (*ServerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ServerInfo",
			Handler:    _ServerService_ServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_server_5af9ff290d7e433b) }

var fileDescriptor_server_5af9ff290d7e433b = []byte{
	// 277 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x4f, 0x4e, 0xf3, 0x30,
	0x10, 0xc5, 0xbf, 0x24, 0x52, 0x94, 0x4e, 0x92, 0x0f, 0x30, 0x9b, 0x62, 0x21, 0x51, 0x22, 0x21,
	0x65, 0x95, 0x45, 0xd9, 0xb1, 0x67, 0xc1, 0x86, 0x45, 0x22, 0x75, 0x5b, 0xb9, 0x74, 0x08, 0x96,
	0xd2, 0xb8, 0x78, 0xa6, 0x45, 0x9c, 0x84, 0x23, 0x70, 0x3f, 0x4e, 0x80, 0xb0, 0xfb, 0x0f, 0x01,
	0x1b, 0x4b, 0xf3, 0x9b, 0x37, 0x9e, 0xf7, 0x6c, 0xc8, 0x08, 0xed, 0x1a, 0x6d, 0xb5, 0xb4, 0x86,
	0x8d, 0x88, 0x5b, 0xcd, 0xaa, 0x7b, 0x95, 0x19, 0x3d, 0x29, 0x8b, 0x73, 0x4f, 0x8b, 0x53, 0x38,
	0x69, 0x9c, 0xea, 0xae, 0x7f, 0x34, 0x35, 0x3e, 0xaf, 0x90, 0xb8, 0x78, 0x0f, 0x41, 0x1c, 0x52,
	0x5a, 0x9a, 0x9e, 0x50, 0x5c, 0xc1, 0x7f, 0x7f, 0xe3, 0x74, 0x8d, 0x96, 0xb4, 0xe9, 0x87, 0xc1,
	0x28, 0x28, 0x07, 0x75, 0xee, 0xe9, 0xc4, 0x43, 0x71, 0x01, 0x69, 0xab, 0x79, 0xa7, 0x09, 0x9d,
	0x06, 0x5a, 0xcd, 0x5b, 0x41, 0x03, 0xc7, 0xc4, 0xc6, 0xaa, 0x16, 0xa7, 0xc4, 0x8a, 0x57, 0x84,
	0x34, 0x8c, 0x46, 0x51, 0x99, 0x8e, 0xcb, 0xca, 0x9b, 0xac, 0x7e, 0x6e, 0xaf, 0x1a, 0x3f, 0xd2,
	0xb8, 0x89, 0xfa, 0x88, 0x0e, 0x4b, 0x24, 0xd9, 0x41, 0xfe, 0x4d, 0x21, 0x2e, 0x21, 0xdb, 0x6e,
	0xe9, 0xd5, 0x02, 0x37, 0x5e, 0xd3, 0x0d, 0xbb, 0x57, 0x0b, 0x14, 0x12, 0x12, 0x8b, 0x6a, 0xae,
	0x66, 0x1d, 0x3a, 0x9b, 0x49, 0xbd, 0xab, 0xc5, 0x39, 0x0c, 0x5e, 0xac, 0x66, 0x74, 0xcd, 0xc8,
	0x35, 0xf7, 0xe0, 0x26, 0xfe, 0x78, 0x2b, 0xc3, 0x24, 0x18, 0x4f, 0x20, 0xf7, 0x56, 0xbf, 0x4e,
	0xfd, 0x80, 0xe2, 0x16, 0x60, 0xef, 0x5d, 0x9c, 0xfd, 0x96, 0xc7, 0xbd, 0xb1, 0x94, 0x7f, 0x47,
	0x2d, 0xfe, 0xcd, 0x62, 0xf7, 0x3b, 0xd7, 0x9f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xe5, 0xe1,
	0x6c, 0xc3, 0x01, 0x00, 0x00,
}
