# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deprecated-services.proto

require 'google/protobuf'

require 'commit_pb'
require 'diff_pb'
require 'notifications_pb'
require 'ref_pb'
require 'smarthttp_pb'
require 'ssh_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Gitaly
end
