# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: diff.proto for package 'gitaly'

require 'grpc'
require 'diff_pb'

module Gitaly
  module Diff
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.Diff'

      # Returns stream of CommitDiffResponse: 1 per changed file
      rpc :CommitDiff, CommitDiffRequest, stream(CommitDiffResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
