# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: notifications.proto for package 'gitaly'

require 'grpc'
require 'notifications_pb'

module Gitaly
  module NotificationService
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'gitaly.NotificationService'

      rpc :PostReceive, PostReceiveRequest, PostReceiveResponse
    end

    Stub = Service.rpc_stub_class
  end
end
