# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wiki.proto

require 'google/protobuf'

require 'shared_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "gitaly.WikiPageVersion" do
    optional :commit, :message, 1, "gitaly.GitCommit"
    optional :format, :string, 2
  end
  add_message "gitaly.WikiGetPageVersionsRequest" do
    optional :repository, :message, 1, "gitaly.Repository"
    optional :page_path, :bytes, 2
  end
  add_message "gitaly.WikiGetPageVersionsResponse" do
    repeated :versions, :message, 1, "gitaly.WikiPageVersion"
  end
end

module Gitaly
  WikiPageVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.WikiPageVersion").msgclass
  WikiGetPageVersionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.WikiGetPageVersionsRequest").msgclass
  WikiGetPageVersionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("gitaly.WikiGetPageVersionsResponse").msgclass
end
