=begin
#commit.proto

#No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

OpenAPI spec version: version not set

Generated by: https://github.com/swagger-api/swagger-codegen.git

=end

require 'date'

module SwaggerClient
  class FindLocalBranchesRequestSortBy
    
    NAME = "NAME".freeze
    UPDATED_ASC = "UPDATED_ASC".freeze
    UPDATED_DESC = "UPDATED_DESC".freeze
  end

end
